//! `BleAdapter` — UniFFI foreign-trait projection (sync, by-value).
//!
//! Mirrors `iris_core::transport::ble::BleAdapter` (10-op) with **owned,
//! UniFFI-supported types** (issue #2263: no references across FFI). The real
//! trait's `MutexGuard`-returning drains (`incoming_gatt_writes()`,
//! `scan_results()`) become `Vec`-returning drain ops — a recorded spike
//! finding (proj-BLE-1). FfiConversions are generated by UniFFI for the
//! `#[record]` types below.

use crate::ffi::error::IrisFfiError;

/// Owned scan filter (mirrors `ble::ScanFilter` fields flattened to FFI-safe).
#[derive(Debug, Clone, Default, uniffi::Record)]
pub struct FfiScanFilter {
    /// Service UUID hex ("" = all).
    pub service_uuid: String,
    /// Address to filter on ("" = any).
    pub address: String,
    /// RSSI floor dBm (e.g. -95).
    pub rssi_floor: i32,
}

/// Owned advertisement payload for the discovery beacon (`ble::AdvertisementData`).
#[derive(Debug, Clone, uniffi::Record)]
pub struct FfiAdvertisementData {
    /// Raw bytes the platform must advertise.
    pub payload: Vec<u8>,
    /// When true, advertise as non-connectable (broadcast beacon).
    pub non_connectable: bool,
}

/// Owned scan-result drain (`ble::ScanResult`; replaces the MutexGuard drain).
#[derive(Debug, Clone, uniffi::Record)]
pub struct FfiScanResult {
    pub address: String,
    pub payload: Vec<u8>,
    pub rssi: i32,
}

/// Owned inbound GATT write (`ble::GattWriteEvent`; replaces the MutexGuard drain).
#[derive(Debug, Clone, uniffi::Record)]
pub struct FfiGattWriteEvent {
    /// Peer attribute handle.
    pub handle: u64,
    /// Characteristic UUID hex.
    pub char_uuid: String,
    pub data: Vec<u8>,
}

/// Foreign-trait projection of `ble::BleAdapter`. Implemented by
/// `AndroidBleTransportAdapter` (Kotlin); simulated in Rust unit tests.
#[uniffi::export(with_foreign)]
pub trait FfiBleAdapter: Send + Sync + 'static {
    fn start_scan(&self, filter: FfiScanFilter) -> Result<u64, IrisFfiError>;
    fn stop_scan(&self, handle: u64);
    fn start_advertising(&self, data: FfiAdvertisementData) -> Result<u64, IrisFfiError>;
    fn stop_advertising(&self, handle: u64);
    fn connect_gatt(&self, address: String) -> Result<u64, IrisFfiError>;
    fn disconnect_gatt(&self, handle: u64);
    fn gatt_write(&self, handle: u64, char_uuid: String, data: Vec<u8>)
        -> Result<(), IrisFfiError>;
    fn set_mtu(&self, handle: u64, mtu: u16) -> Result<u16, IrisFfiError>;
    /// Drain inbound GATT writes (projection of the MutexGuard drain).
    fn incoming_gatt_writes(&self) -> Vec<FfiGattWriteEvent>;
    /// Drain scan results (projection of the MutexGuard drain).
    fn scan_results(&self) -> Vec<FfiScanResult>;
}

#[cfg(test)]
pub(crate) mod tests {
    use super::*;

    /// Rust-side simulated adapter: proves the projection trait can be driven
    /// by a plain Rust implementation (the Kotlin side is the FFI twin).
    pub(crate) struct SimBle;
    impl FfiBleAdapter for SimBle {
        fn start_scan(&self, _f: FfiScanFilter) -> Result<u64, IrisFfiError> {
            Ok(7)
        }
        fn stop_scan(&self, _h: u64) {}
        fn start_advertising(&self, _d: FfiAdvertisementData) -> Result<u64, IrisFfiError> {
            Ok(9)
        }
        fn stop_advertising(&self, _h: u64) {}
        fn connect_gatt(&self, _a: String) -> Result<u64, IrisFfiError> {
            Ok(11)
        }
        fn disconnect_gatt(&self, _h: u64) {}
        fn gatt_write(&self, _h: u64, _c: String, data: Vec<u8>) -> Result<(), IrisFfiError> {
            assert_eq!(data, b"hi".to_vec());
            Ok(())
        }
        fn set_mtu(&self, _h: u64, mtu: u16) -> Result<u16, IrisFfiError> {
            Ok(mtu.max(512))
        }
        fn incoming_gatt_writes(&self) -> Vec<FfiGattWriteEvent> {
            Vec::new()
        }
        fn scan_results(&self) -> Vec<FfiScanResult> {
            Vec::new()
        }
    }

    #[test]
    fn projection_trait_drives_sync_ops() {
        let a = SimBle;
        assert_eq!(a.start_scan(FfiScanFilter::default()).unwrap(), 7);
        assert_eq!(a.set_mtu(1, 300).unwrap(), 512);
        let _ = (|| -> Result<String, IrisFfiError> {
            a.start_scan(FfiScanFilter {
                service_uuid: String::new(),
                address: String::new(),
                rssi_floor: -95,
            })?;
            Ok(String::new())
        },);
    }
}
