// This file was autogenerated by some hot garbage in the `uniffi` crate.
// Trust me, you don't want to mess with it!

#pragma once

#include <stdbool.h>
#include <stddef.h>
#include <stdint.h>

// The following structs are used to implement the lowest level
// of the FFI, and thus useful to multiple uniffied crates.
// We ensure they are declared exactly once, with a header guard, UNIFFI_SHARED_H.
#ifdef UNIFFI_SHARED_H
    // We also try to prevent mixing versions of shared uniffi header structs.
    // If you add anything to the #else block, you must increment the version suffix in UNIFFI_SHARED_HEADER_V4
    #ifndef UNIFFI_SHARED_HEADER_V4
        #error Combining helper code from multiple versions of uniffi is not supported
    #endif // ndef UNIFFI_SHARED_HEADER_V4
#else
#define UNIFFI_SHARED_H
#define UNIFFI_SHARED_HEADER_V4
// ⚠️ Attention: If you change this #else block (ending in `#endif // def UNIFFI_SHARED_H`) you *must* ⚠️
// ⚠️ increment the version suffix in all instances of UNIFFI_SHARED_HEADER_V4 in this file.           ⚠️

typedef struct RustBuffer
{
    uint64_t capacity;
    uint64_t len;
    uint8_t *_Nullable data;
} RustBuffer;

typedef struct ForeignBytes
{
    int32_t len;
    const uint8_t *_Nullable data;
} ForeignBytes;

// Error definitions
typedef struct RustCallStatus {
    int8_t code;
    RustBuffer errorBuf;
} RustCallStatus;

// ⚠️ Attention: If you change this #else block (ending in `#endif // def UNIFFI_SHARED_H`) you *must* ⚠️
// ⚠️ increment the version suffix in all instances of UNIFFI_SHARED_HEADER_V4 in this file.           ⚠️
#endif // def UNIFFI_SHARED_H
#ifndef UNIFFI_FFIDEF_RUST_FUTURE_CONTINUATION_CALLBACK
#define UNIFFI_FFIDEF_RUST_FUTURE_CONTINUATION_CALLBACK
typedef void (*UniffiRustFutureContinuationCallback)(uint64_t, int8_t
    );

#endif
#ifndef UNIFFI_FFIDEF_FOREIGN_FUTURE_DROPPED_CALLBACK
#define UNIFFI_FFIDEF_FOREIGN_FUTURE_DROPPED_CALLBACK
typedef void (*UniffiForeignFutureDroppedCallback)(uint64_t
    );

#endif
#ifndef UNIFFI_FFIDEF_CALLBACK_INTERFACE_FREE
#define UNIFFI_FFIDEF_CALLBACK_INTERFACE_FREE
typedef void (*UniffiCallbackInterfaceFree)(uint64_t
    );

#endif
#ifndef UNIFFI_FFIDEF_CALLBACK_INTERFACE_CLONE
#define UNIFFI_FFIDEF_CALLBACK_INTERFACE_CLONE
typedef uint64_t (*UniffiCallbackInterfaceClone)(uint64_t
    );

#endif
#ifndef UNIFFI_FFIDEF_FOREIGN_FUTURE_DROPPED_CALLBACK_STRUCT
#define UNIFFI_FFIDEF_FOREIGN_FUTURE_DROPPED_CALLBACK_STRUCT
typedef struct UniffiForeignFutureDroppedCallbackStruct {
    uint64_t handle;
    UniffiForeignFutureDroppedCallback _Nonnull free;
} UniffiForeignFutureDroppedCallbackStruct;

#endif
#ifndef UNIFFI_FFIDEF_FOREIGN_FUTURE_RESULT_U8
#define UNIFFI_FFIDEF_FOREIGN_FUTURE_RESULT_U8
typedef struct UniffiForeignFutureResultU8 {
    uint8_t returnValue;
    RustCallStatus callStatus;
} UniffiForeignFutureResultU8;

#endif
#ifndef UNIFFI_FFIDEF_FOREIGN_FUTURE_COMPLETE_U8
#define UNIFFI_FFIDEF_FOREIGN_FUTURE_COMPLETE_U8
typedef void (*UniffiForeignFutureCompleteU8)(uint64_t, UniffiForeignFutureResultU8
    );

#endif
#ifndef UNIFFI_FFIDEF_FOREIGN_FUTURE_RESULT_I8
#define UNIFFI_FFIDEF_FOREIGN_FUTURE_RESULT_I8
typedef struct UniffiForeignFutureResultI8 {
    int8_t returnValue;
    RustCallStatus callStatus;
} UniffiForeignFutureResultI8;

#endif
#ifndef UNIFFI_FFIDEF_FOREIGN_FUTURE_COMPLETE_I8
#define UNIFFI_FFIDEF_FOREIGN_FUTURE_COMPLETE_I8
typedef void (*UniffiForeignFutureCompleteI8)(uint64_t, UniffiForeignFutureResultI8
    );

#endif
#ifndef UNIFFI_FFIDEF_FOREIGN_FUTURE_RESULT_U16
#define UNIFFI_FFIDEF_FOREIGN_FUTURE_RESULT_U16
typedef struct UniffiForeignFutureResultU16 {
    uint16_t returnValue;
    RustCallStatus callStatus;
} UniffiForeignFutureResultU16;

#endif
#ifndef UNIFFI_FFIDEF_FOREIGN_FUTURE_COMPLETE_U16
#define UNIFFI_FFIDEF_FOREIGN_FUTURE_COMPLETE_U16
typedef void (*UniffiForeignFutureCompleteU16)(uint64_t, UniffiForeignFutureResultU16
    );

#endif
#ifndef UNIFFI_FFIDEF_FOREIGN_FUTURE_RESULT_I16
#define UNIFFI_FFIDEF_FOREIGN_FUTURE_RESULT_I16
typedef struct UniffiForeignFutureResultI16 {
    int16_t returnValue;
    RustCallStatus callStatus;
} UniffiForeignFutureResultI16;

#endif
#ifndef UNIFFI_FFIDEF_FOREIGN_FUTURE_COMPLETE_I16
#define UNIFFI_FFIDEF_FOREIGN_FUTURE_COMPLETE_I16
typedef void (*UniffiForeignFutureCompleteI16)(uint64_t, UniffiForeignFutureResultI16
    );

#endif
#ifndef UNIFFI_FFIDEF_FOREIGN_FUTURE_RESULT_U32
#define UNIFFI_FFIDEF_FOREIGN_FUTURE_RESULT_U32
typedef struct UniffiForeignFutureResultU32 {
    uint32_t returnValue;
    RustCallStatus callStatus;
} UniffiForeignFutureResultU32;

#endif
#ifndef UNIFFI_FFIDEF_FOREIGN_FUTURE_COMPLETE_U32
#define UNIFFI_FFIDEF_FOREIGN_FUTURE_COMPLETE_U32
typedef void (*UniffiForeignFutureCompleteU32)(uint64_t, UniffiForeignFutureResultU32
    );

#endif
#ifndef UNIFFI_FFIDEF_FOREIGN_FUTURE_RESULT_I32
#define UNIFFI_FFIDEF_FOREIGN_FUTURE_RESULT_I32
typedef struct UniffiForeignFutureResultI32 {
    int32_t returnValue;
    RustCallStatus callStatus;
} UniffiForeignFutureResultI32;

#endif
#ifndef UNIFFI_FFIDEF_FOREIGN_FUTURE_COMPLETE_I32
#define UNIFFI_FFIDEF_FOREIGN_FUTURE_COMPLETE_I32
typedef void (*UniffiForeignFutureCompleteI32)(uint64_t, UniffiForeignFutureResultI32
    );

#endif
#ifndef UNIFFI_FFIDEF_FOREIGN_FUTURE_RESULT_U64
#define UNIFFI_FFIDEF_FOREIGN_FUTURE_RESULT_U64
typedef struct UniffiForeignFutureResultU64 {
    uint64_t returnValue;
    RustCallStatus callStatus;
} UniffiForeignFutureResultU64;

#endif
#ifndef UNIFFI_FFIDEF_FOREIGN_FUTURE_COMPLETE_U64
#define UNIFFI_FFIDEF_FOREIGN_FUTURE_COMPLETE_U64
typedef void (*UniffiForeignFutureCompleteU64)(uint64_t, UniffiForeignFutureResultU64
    );

#endif
#ifndef UNIFFI_FFIDEF_FOREIGN_FUTURE_RESULT_I64
#define UNIFFI_FFIDEF_FOREIGN_FUTURE_RESULT_I64
typedef struct UniffiForeignFutureResultI64 {
    int64_t returnValue;
    RustCallStatus callStatus;
} UniffiForeignFutureResultI64;

#endif
#ifndef UNIFFI_FFIDEF_FOREIGN_FUTURE_COMPLETE_I64
#define UNIFFI_FFIDEF_FOREIGN_FUTURE_COMPLETE_I64
typedef void (*UniffiForeignFutureCompleteI64)(uint64_t, UniffiForeignFutureResultI64
    );

#endif
#ifndef UNIFFI_FFIDEF_FOREIGN_FUTURE_RESULT_F32
#define UNIFFI_FFIDEF_FOREIGN_FUTURE_RESULT_F32
typedef struct UniffiForeignFutureResultF32 {
    float returnValue;
    RustCallStatus callStatus;
} UniffiForeignFutureResultF32;

#endif
#ifndef UNIFFI_FFIDEF_FOREIGN_FUTURE_COMPLETE_F32
#define UNIFFI_FFIDEF_FOREIGN_FUTURE_COMPLETE_F32
typedef void (*UniffiForeignFutureCompleteF32)(uint64_t, UniffiForeignFutureResultF32
    );

#endif
#ifndef UNIFFI_FFIDEF_FOREIGN_FUTURE_RESULT_F64
#define UNIFFI_FFIDEF_FOREIGN_FUTURE_RESULT_F64
typedef struct UniffiForeignFutureResultF64 {
    double returnValue;
    RustCallStatus callStatus;
} UniffiForeignFutureResultF64;

#endif
#ifndef UNIFFI_FFIDEF_FOREIGN_FUTURE_COMPLETE_F64
#define UNIFFI_FFIDEF_FOREIGN_FUTURE_COMPLETE_F64
typedef void (*UniffiForeignFutureCompleteF64)(uint64_t, UniffiForeignFutureResultF64
    );

#endif
#ifndef UNIFFI_FFIDEF_FOREIGN_FUTURE_RESULT_RUST_BUFFER
#define UNIFFI_FFIDEF_FOREIGN_FUTURE_RESULT_RUST_BUFFER
typedef struct UniffiForeignFutureResultRustBuffer {
    RustBuffer returnValue;
    RustCallStatus callStatus;
} UniffiForeignFutureResultRustBuffer;

#endif
#ifndef UNIFFI_FFIDEF_FOREIGN_FUTURE_COMPLETE_RUST_BUFFER
#define UNIFFI_FFIDEF_FOREIGN_FUTURE_COMPLETE_RUST_BUFFER
typedef void (*UniffiForeignFutureCompleteRustBuffer)(uint64_t, UniffiForeignFutureResultRustBuffer
    );

#endif
#ifndef UNIFFI_FFIDEF_FOREIGN_FUTURE_RESULT_VOID
#define UNIFFI_FFIDEF_FOREIGN_FUTURE_RESULT_VOID
typedef struct UniffiForeignFutureResultVoid {
    RustCallStatus callStatus;
} UniffiForeignFutureResultVoid;

#endif
#ifndef UNIFFI_FFIDEF_FOREIGN_FUTURE_COMPLETE_VOID
#define UNIFFI_FFIDEF_FOREIGN_FUTURE_COMPLETE_VOID
typedef void (*UniffiForeignFutureCompleteVoid)(uint64_t, UniffiForeignFutureResultVoid
    );

#endif
#ifndef UNIFFI_FFIDEF_CALLBACK_INTERFACE_FFI_INBOX_LISTENER_METHOD0
#define UNIFFI_FFIDEF_CALLBACK_INTERFACE_FFI_INBOX_LISTENER_METHOD0
typedef void (*UniffiCallbackInterfaceFfiInboxListenerMethod0)(uint64_t, RustBuffer, void* _Nonnull, 
        RustCallStatus *_Nonnull uniffiCallStatus
    );

#endif
#ifndef UNIFFI_FFIDEF_CALLBACK_INTERFACE_FFI_BLE_ADAPTER_METHOD0
#define UNIFFI_FFIDEF_CALLBACK_INTERFACE_FFI_BLE_ADAPTER_METHOD0
typedef void (*UniffiCallbackInterfaceFfiBleAdapterMethod0)(uint64_t, RustBuffer, uint64_t* _Nonnull, 
        RustCallStatus *_Nonnull uniffiCallStatus
    );

#endif
#ifndef UNIFFI_FFIDEF_CALLBACK_INTERFACE_FFI_BLE_ADAPTER_METHOD1
#define UNIFFI_FFIDEF_CALLBACK_INTERFACE_FFI_BLE_ADAPTER_METHOD1
typedef void (*UniffiCallbackInterfaceFfiBleAdapterMethod1)(uint64_t, uint64_t, void* _Nonnull, 
        RustCallStatus *_Nonnull uniffiCallStatus
    );

#endif
#ifndef UNIFFI_FFIDEF_CALLBACK_INTERFACE_FFI_BLE_ADAPTER_METHOD2
#define UNIFFI_FFIDEF_CALLBACK_INTERFACE_FFI_BLE_ADAPTER_METHOD2
typedef void (*UniffiCallbackInterfaceFfiBleAdapterMethod2)(uint64_t, RustBuffer, uint64_t* _Nonnull, 
        RustCallStatus *_Nonnull uniffiCallStatus
    );

#endif
#ifndef UNIFFI_FFIDEF_CALLBACK_INTERFACE_FFI_BLE_ADAPTER_METHOD3
#define UNIFFI_FFIDEF_CALLBACK_INTERFACE_FFI_BLE_ADAPTER_METHOD3
typedef void (*UniffiCallbackInterfaceFfiBleAdapterMethod3)(uint64_t, uint64_t, void* _Nonnull, 
        RustCallStatus *_Nonnull uniffiCallStatus
    );

#endif
#ifndef UNIFFI_FFIDEF_CALLBACK_INTERFACE_FFI_BLE_ADAPTER_METHOD4
#define UNIFFI_FFIDEF_CALLBACK_INTERFACE_FFI_BLE_ADAPTER_METHOD4
typedef void (*UniffiCallbackInterfaceFfiBleAdapterMethod4)(uint64_t, RustBuffer, uint64_t* _Nonnull, 
        RustCallStatus *_Nonnull uniffiCallStatus
    );

#endif
#ifndef UNIFFI_FFIDEF_CALLBACK_INTERFACE_FFI_BLE_ADAPTER_METHOD5
#define UNIFFI_FFIDEF_CALLBACK_INTERFACE_FFI_BLE_ADAPTER_METHOD5
typedef void (*UniffiCallbackInterfaceFfiBleAdapterMethod5)(uint64_t, uint64_t, void* _Nonnull, 
        RustCallStatus *_Nonnull uniffiCallStatus
    );

#endif
#ifndef UNIFFI_FFIDEF_CALLBACK_INTERFACE_FFI_BLE_ADAPTER_METHOD6
#define UNIFFI_FFIDEF_CALLBACK_INTERFACE_FFI_BLE_ADAPTER_METHOD6
typedef void (*UniffiCallbackInterfaceFfiBleAdapterMethod6)(uint64_t, uint64_t, RustBuffer, RustBuffer, void* _Nonnull, 
        RustCallStatus *_Nonnull uniffiCallStatus
    );

#endif
#ifndef UNIFFI_FFIDEF_CALLBACK_INTERFACE_FFI_BLE_ADAPTER_METHOD7
#define UNIFFI_FFIDEF_CALLBACK_INTERFACE_FFI_BLE_ADAPTER_METHOD7
typedef void (*UniffiCallbackInterfaceFfiBleAdapterMethod7)(uint64_t, uint64_t, RustBuffer, RustBuffer* _Nonnull, 
        RustCallStatus *_Nonnull uniffiCallStatus
    );

#endif
#ifndef UNIFFI_FFIDEF_CALLBACK_INTERFACE_FFI_BLE_ADAPTER_METHOD8
#define UNIFFI_FFIDEF_CALLBACK_INTERFACE_FFI_BLE_ADAPTER_METHOD8
typedef void (*UniffiCallbackInterfaceFfiBleAdapterMethod8)(uint64_t, uint64_t, uint16_t, uint16_t* _Nonnull, 
        RustCallStatus *_Nonnull uniffiCallStatus
    );

#endif
#ifndef UNIFFI_FFIDEF_CALLBACK_INTERFACE_FFI_BLE_ADAPTER_METHOD9
#define UNIFFI_FFIDEF_CALLBACK_INTERFACE_FFI_BLE_ADAPTER_METHOD9
typedef void (*UniffiCallbackInterfaceFfiBleAdapterMethod9)(uint64_t, RustBuffer* _Nonnull, 
        RustCallStatus *_Nonnull uniffiCallStatus
    );

#endif
#ifndef UNIFFI_FFIDEF_CALLBACK_INTERFACE_FFI_BLE_ADAPTER_METHOD10
#define UNIFFI_FFIDEF_CALLBACK_INTERFACE_FFI_BLE_ADAPTER_METHOD10
typedef void (*UniffiCallbackInterfaceFfiBleAdapterMethod10)(uint64_t, RustBuffer* _Nonnull, 
        RustCallStatus *_Nonnull uniffiCallStatus
    );

#endif
#ifndef UNIFFI_FFIDEF_CALLBACK_INTERFACE_IRIS_BODY_METHOD0
#define UNIFFI_FFIDEF_CALLBACK_INTERFACE_IRIS_BODY_METHOD0
typedef void (*UniffiCallbackInterfaceIrisBodyMethod0)(uint64_t, RustBuffer, RustBuffer* _Nonnull, 
        RustCallStatus *_Nonnull uniffiCallStatus
    );

#endif
#ifndef UNIFFI_FFIDEF_CALLBACK_INTERFACE_IRIS_BODY_METHOD1
#define UNIFFI_FFIDEF_CALLBACK_INTERFACE_IRIS_BODY_METHOD1
typedef void (*UniffiCallbackInterfaceIrisBodyMethod1)(uint64_t, RustBuffer, UniffiForeignFutureCompleteRustBuffer _Nonnull, uint64_t, UniffiForeignFutureDroppedCallbackStruct* _Nonnull
    );

#endif
#ifndef UNIFFI_FFIDEF_V_TABLE_CALLBACK_INTERFACE_FFI_INBOX_LISTENER
#define UNIFFI_FFIDEF_V_TABLE_CALLBACK_INTERFACE_FFI_INBOX_LISTENER
typedef struct UniffiVTableCallbackInterfaceFfiInboxListener {
    UniffiCallbackInterfaceFree _Nonnull uniffiFree;
    UniffiCallbackInterfaceClone _Nonnull uniffiClone;
    UniffiCallbackInterfaceFfiInboxListenerMethod0 _Nonnull onMessage;
} UniffiVTableCallbackInterfaceFfiInboxListener;

#endif
#ifndef UNIFFI_FFIDEF_V_TABLE_CALLBACK_INTERFACE_FFI_BLE_ADAPTER
#define UNIFFI_FFIDEF_V_TABLE_CALLBACK_INTERFACE_FFI_BLE_ADAPTER
typedef struct UniffiVTableCallbackInterfaceFfiBleAdapter {
    UniffiCallbackInterfaceFree _Nonnull uniffiFree;
    UniffiCallbackInterfaceClone _Nonnull uniffiClone;
    UniffiCallbackInterfaceFfiBleAdapterMethod0 _Nonnull startScan;
    UniffiCallbackInterfaceFfiBleAdapterMethod1 _Nonnull stopScan;
    UniffiCallbackInterfaceFfiBleAdapterMethod2 _Nonnull startAdvertising;
    UniffiCallbackInterfaceFfiBleAdapterMethod3 _Nonnull stopAdvertising;
    UniffiCallbackInterfaceFfiBleAdapterMethod4 _Nonnull connectGatt;
    UniffiCallbackInterfaceFfiBleAdapterMethod5 _Nonnull disconnectGatt;
    UniffiCallbackInterfaceFfiBleAdapterMethod6 _Nonnull gattWrite;
    UniffiCallbackInterfaceFfiBleAdapterMethod7 _Nonnull gattRead;
    UniffiCallbackInterfaceFfiBleAdapterMethod8 _Nonnull setMtu;
    UniffiCallbackInterfaceFfiBleAdapterMethod9 _Nonnull incomingGattWrites;
    UniffiCallbackInterfaceFfiBleAdapterMethod10 _Nonnull scanResults;
} UniffiVTableCallbackInterfaceFfiBleAdapter;

#endif
#ifndef UNIFFI_FFIDEF_V_TABLE_CALLBACK_INTERFACE_IRIS_BODY
#define UNIFFI_FFIDEF_V_TABLE_CALLBACK_INTERFACE_IRIS_BODY
typedef struct UniffiVTableCallbackInterfaceIrisBody {
    UniffiCallbackInterfaceFree _Nonnull uniffiFree;
    UniffiCallbackInterfaceClone _Nonnull uniffiClone;
    UniffiCallbackInterfaceIrisBodyMethod0 _Nonnull summarize;
    UniffiCallbackInterfaceIrisBodyMethod1 _Nonnull describe;
} UniffiVTableCallbackInterfaceIrisBody;

#endif
#ifndef UNIFFI_FFIDEF_UNIFFI_IRIS_CORE_FN_CLONE_FFIINBOXLISTENER
#define UNIFFI_FFIDEF_UNIFFI_IRIS_CORE_FN_CLONE_FFIINBOXLISTENER
uint64_t uniffi_IrisCore_fn_clone_ffiinboxlistener(uint64_t handle, RustCallStatus *_Nonnull out_status
);
#endif
#ifndef UNIFFI_FFIDEF_UNIFFI_IRIS_CORE_FN_FREE_FFIINBOXLISTENER
#define UNIFFI_FFIDEF_UNIFFI_IRIS_CORE_FN_FREE_FFIINBOXLISTENER
void uniffi_IrisCore_fn_free_ffiinboxlistener(uint64_t handle, RustCallStatus *_Nonnull out_status
);
#endif
#ifndef UNIFFI_FFIDEF_UNIFFI_IRIS_CORE_FN_INIT_CALLBACK_VTABLE_FFIINBOXLISTENER
#define UNIFFI_FFIDEF_UNIFFI_IRIS_CORE_FN_INIT_CALLBACK_VTABLE_FFIINBOXLISTENER
void uniffi_IrisCore_fn_init_callback_vtable_ffiinboxlistener(const UniffiVTableCallbackInterfaceFfiInboxListener* _Nonnull vtable
);
#endif
#ifndef UNIFFI_FFIDEF_UNIFFI_IRIS_CORE_FN_METHOD_FFIINBOXLISTENER_ON_MESSAGE
#define UNIFFI_FFIDEF_UNIFFI_IRIS_CORE_FN_METHOD_FFIINBOXLISTENER_ON_MESSAGE
void uniffi_IrisCore_fn_method_ffiinboxlistener_on_message(uint64_t ptr, RustBuffer message, RustCallStatus *_Nonnull out_status
);
#endif
#ifndef UNIFFI_FFIDEF_UNIFFI_IRIS_CORE_FN_CLONE_IRISENGINE
#define UNIFFI_FFIDEF_UNIFFI_IRIS_CORE_FN_CLONE_IRISENGINE
uint64_t uniffi_IrisCore_fn_clone_irisengine(uint64_t handle, RustCallStatus *_Nonnull out_status
);
#endif
#ifndef UNIFFI_FFIDEF_UNIFFI_IRIS_CORE_FN_FREE_IRISENGINE
#define UNIFFI_FFIDEF_UNIFFI_IRIS_CORE_FN_FREE_IRISENGINE
void uniffi_IrisCore_fn_free_irisengine(uint64_t handle, RustCallStatus *_Nonnull out_status
);
#endif
#ifndef UNIFFI_FFIDEF_UNIFFI_IRIS_CORE_FN_CONSTRUCTOR_IRISENGINE_NEW
#define UNIFFI_FFIDEF_UNIFFI_IRIS_CORE_FN_CONSTRUCTOR_IRISENGINE_NEW
uint64_t uniffi_IrisCore_fn_constructor_irisengine_new(uint64_t ble, RustBuffer node_id, RustCallStatus *_Nonnull out_status
);
#endif
#ifndef UNIFFI_FFIDEF_UNIFFI_IRIS_CORE_FN_METHOD_IRISENGINE_NODE_ID
#define UNIFFI_FFIDEF_UNIFFI_IRIS_CORE_FN_METHOD_IRISENGINE_NODE_ID
RustBuffer uniffi_IrisCore_fn_method_irisengine_node_id(uint64_t ptr, RustCallStatus *_Nonnull out_status
);
#endif
#ifndef UNIFFI_FFIDEF_UNIFFI_IRIS_CORE_FN_METHOD_IRISENGINE_SEND_TEXT
#define UNIFFI_FFIDEF_UNIFFI_IRIS_CORE_FN_METHOD_IRISENGINE_SEND_TEXT
RustBuffer uniffi_IrisCore_fn_method_irisengine_send_text(uint64_t ptr, RustBuffer recipient_hex, RustBuffer text, uint8_t priority, RustCallStatus *_Nonnull out_status
);
#endif
#ifndef UNIFFI_FFIDEF_UNIFFI_IRIS_CORE_FN_METHOD_IRISENGINE_SET_BODY_RENDERER
#define UNIFFI_FFIDEF_UNIFFI_IRIS_CORE_FN_METHOD_IRISENGINE_SET_BODY_RENDERER
void uniffi_IrisCore_fn_method_irisengine_set_body_renderer(uint64_t ptr, uint64_t renderer, RustCallStatus *_Nonnull out_status
);
#endif
#ifndef UNIFFI_FFIDEF_UNIFFI_IRIS_CORE_FN_METHOD_IRISENGINE_START_ALL
#define UNIFFI_FFIDEF_UNIFFI_IRIS_CORE_FN_METHOD_IRISENGINE_START_ALL
void uniffi_IrisCore_fn_method_irisengine_start_all(uint64_t ptr, RustCallStatus *_Nonnull out_status
);
#endif
#ifndef UNIFFI_FFIDEF_UNIFFI_IRIS_CORE_FN_METHOD_IRISENGINE_STOP_ALL
#define UNIFFI_FFIDEF_UNIFFI_IRIS_CORE_FN_METHOD_IRISENGINE_STOP_ALL
void uniffi_IrisCore_fn_method_irisengine_stop_all(uint64_t ptr, RustCallStatus *_Nonnull out_status
);
#endif
#ifndef UNIFFI_FFIDEF_UNIFFI_IRIS_CORE_FN_METHOD_IRISENGINE_SUBSCRIBE_INBOX
#define UNIFFI_FFIDEF_UNIFFI_IRIS_CORE_FN_METHOD_IRISENGINE_SUBSCRIBE_INBOX
void uniffi_IrisCore_fn_method_irisengine_subscribe_inbox(uint64_t ptr, uint64_t listener, RustCallStatus *_Nonnull out_status
);
#endif
#ifndef UNIFFI_FFIDEF_UNIFFI_IRIS_CORE_FN_CLONE_FFIBLEADAPTER
#define UNIFFI_FFIDEF_UNIFFI_IRIS_CORE_FN_CLONE_FFIBLEADAPTER
uint64_t uniffi_IrisCore_fn_clone_ffibleadapter(uint64_t handle, RustCallStatus *_Nonnull out_status
);
#endif
#ifndef UNIFFI_FFIDEF_UNIFFI_IRIS_CORE_FN_FREE_FFIBLEADAPTER
#define UNIFFI_FFIDEF_UNIFFI_IRIS_CORE_FN_FREE_FFIBLEADAPTER
void uniffi_IrisCore_fn_free_ffibleadapter(uint64_t handle, RustCallStatus *_Nonnull out_status
);
#endif
#ifndef UNIFFI_FFIDEF_UNIFFI_IRIS_CORE_FN_INIT_CALLBACK_VTABLE_FFIBLEADAPTER
#define UNIFFI_FFIDEF_UNIFFI_IRIS_CORE_FN_INIT_CALLBACK_VTABLE_FFIBLEADAPTER
void uniffi_IrisCore_fn_init_callback_vtable_ffibleadapter(const UniffiVTableCallbackInterfaceFfiBleAdapter* _Nonnull vtable
);
#endif
#ifndef UNIFFI_FFIDEF_UNIFFI_IRIS_CORE_FN_METHOD_FFIBLEADAPTER_START_SCAN
#define UNIFFI_FFIDEF_UNIFFI_IRIS_CORE_FN_METHOD_FFIBLEADAPTER_START_SCAN
uint64_t uniffi_IrisCore_fn_method_ffibleadapter_start_scan(uint64_t ptr, RustBuffer filter, RustCallStatus *_Nonnull out_status
);
#endif
#ifndef UNIFFI_FFIDEF_UNIFFI_IRIS_CORE_FN_METHOD_FFIBLEADAPTER_STOP_SCAN
#define UNIFFI_FFIDEF_UNIFFI_IRIS_CORE_FN_METHOD_FFIBLEADAPTER_STOP_SCAN
void uniffi_IrisCore_fn_method_ffibleadapter_stop_scan(uint64_t ptr, uint64_t handle, RustCallStatus *_Nonnull out_status
);
#endif
#ifndef UNIFFI_FFIDEF_UNIFFI_IRIS_CORE_FN_METHOD_FFIBLEADAPTER_START_ADVERTISING
#define UNIFFI_FFIDEF_UNIFFI_IRIS_CORE_FN_METHOD_FFIBLEADAPTER_START_ADVERTISING
uint64_t uniffi_IrisCore_fn_method_ffibleadapter_start_advertising(uint64_t ptr, RustBuffer data, RustCallStatus *_Nonnull out_status
);
#endif
#ifndef UNIFFI_FFIDEF_UNIFFI_IRIS_CORE_FN_METHOD_FFIBLEADAPTER_STOP_ADVERTISING
#define UNIFFI_FFIDEF_UNIFFI_IRIS_CORE_FN_METHOD_FFIBLEADAPTER_STOP_ADVERTISING
void uniffi_IrisCore_fn_method_ffibleadapter_stop_advertising(uint64_t ptr, uint64_t handle, RustCallStatus *_Nonnull out_status
);
#endif
#ifndef UNIFFI_FFIDEF_UNIFFI_IRIS_CORE_FN_METHOD_FFIBLEADAPTER_CONNECT_GATT
#define UNIFFI_FFIDEF_UNIFFI_IRIS_CORE_FN_METHOD_FFIBLEADAPTER_CONNECT_GATT
uint64_t uniffi_IrisCore_fn_method_ffibleadapter_connect_gatt(uint64_t ptr, RustBuffer address, RustCallStatus *_Nonnull out_status
);
#endif
#ifndef UNIFFI_FFIDEF_UNIFFI_IRIS_CORE_FN_METHOD_FFIBLEADAPTER_DISCONNECT_GATT
#define UNIFFI_FFIDEF_UNIFFI_IRIS_CORE_FN_METHOD_FFIBLEADAPTER_DISCONNECT_GATT
void uniffi_IrisCore_fn_method_ffibleadapter_disconnect_gatt(uint64_t ptr, uint64_t handle, RustCallStatus *_Nonnull out_status
);
#endif
#ifndef UNIFFI_FFIDEF_UNIFFI_IRIS_CORE_FN_METHOD_FFIBLEADAPTER_GATT_WRITE
#define UNIFFI_FFIDEF_UNIFFI_IRIS_CORE_FN_METHOD_FFIBLEADAPTER_GATT_WRITE
void uniffi_IrisCore_fn_method_ffibleadapter_gatt_write(uint64_t ptr, uint64_t handle, RustBuffer char_uuid, RustBuffer data, RustCallStatus *_Nonnull out_status
);
#endif
#ifndef UNIFFI_FFIDEF_UNIFFI_IRIS_CORE_FN_METHOD_FFIBLEADAPTER_GATT_READ
#define UNIFFI_FFIDEF_UNIFFI_IRIS_CORE_FN_METHOD_FFIBLEADAPTER_GATT_READ
RustBuffer uniffi_IrisCore_fn_method_ffibleadapter_gatt_read(uint64_t ptr, uint64_t handle, RustBuffer char_uuid, RustCallStatus *_Nonnull out_status
);
#endif
#ifndef UNIFFI_FFIDEF_UNIFFI_IRIS_CORE_FN_METHOD_FFIBLEADAPTER_SET_MTU
#define UNIFFI_FFIDEF_UNIFFI_IRIS_CORE_FN_METHOD_FFIBLEADAPTER_SET_MTU
uint16_t uniffi_IrisCore_fn_method_ffibleadapter_set_mtu(uint64_t ptr, uint64_t handle, uint16_t mtu, RustCallStatus *_Nonnull out_status
);
#endif
#ifndef UNIFFI_FFIDEF_UNIFFI_IRIS_CORE_FN_METHOD_FFIBLEADAPTER_INCOMING_GATT_WRITES
#define UNIFFI_FFIDEF_UNIFFI_IRIS_CORE_FN_METHOD_FFIBLEADAPTER_INCOMING_GATT_WRITES
RustBuffer uniffi_IrisCore_fn_method_ffibleadapter_incoming_gatt_writes(uint64_t ptr, RustCallStatus *_Nonnull out_status
);
#endif
#ifndef UNIFFI_FFIDEF_UNIFFI_IRIS_CORE_FN_METHOD_FFIBLEADAPTER_SCAN_RESULTS
#define UNIFFI_FFIDEF_UNIFFI_IRIS_CORE_FN_METHOD_FFIBLEADAPTER_SCAN_RESULTS
RustBuffer uniffi_IrisCore_fn_method_ffibleadapter_scan_results(uint64_t ptr, RustCallStatus *_Nonnull out_status
);
#endif
#ifndef UNIFFI_FFIDEF_UNIFFI_IRIS_CORE_FN_CLONE_IRISBODY
#define UNIFFI_FFIDEF_UNIFFI_IRIS_CORE_FN_CLONE_IRISBODY
uint64_t uniffi_IrisCore_fn_clone_irisbody(uint64_t handle, RustCallStatus *_Nonnull out_status
);
#endif
#ifndef UNIFFI_FFIDEF_UNIFFI_IRIS_CORE_FN_FREE_IRISBODY
#define UNIFFI_FFIDEF_UNIFFI_IRIS_CORE_FN_FREE_IRISBODY
void uniffi_IrisCore_fn_free_irisbody(uint64_t handle, RustCallStatus *_Nonnull out_status
);
#endif
#ifndef UNIFFI_FFIDEF_UNIFFI_IRIS_CORE_FN_INIT_CALLBACK_VTABLE_IRISBODY
#define UNIFFI_FFIDEF_UNIFFI_IRIS_CORE_FN_INIT_CALLBACK_VTABLE_IRISBODY
void uniffi_IrisCore_fn_init_callback_vtable_irisbody(const UniffiVTableCallbackInterfaceIrisBody* _Nonnull vtable
);
#endif
#ifndef UNIFFI_FFIDEF_UNIFFI_IRIS_CORE_FN_METHOD_IRISBODY_SUMMARIZE
#define UNIFFI_FFIDEF_UNIFFI_IRIS_CORE_FN_METHOD_IRISBODY_SUMMARIZE
RustBuffer uniffi_IrisCore_fn_method_irisbody_summarize(uint64_t ptr, RustBuffer envelope, RustCallStatus *_Nonnull out_status
);
#endif
#ifndef UNIFFI_FFIDEF_UNIFFI_IRIS_CORE_FN_METHOD_IRISBODY_DESCRIBE
#define UNIFFI_FFIDEF_UNIFFI_IRIS_CORE_FN_METHOD_IRISBODY_DESCRIBE
uint64_t uniffi_IrisCore_fn_method_irisbody_describe(uint64_t ptr, RustBuffer envelope
);
#endif
#ifndef UNIFFI_FFIDEF_FFI_IRIS_CORE_RUSTBUFFER_ALLOC
#define UNIFFI_FFIDEF_FFI_IRIS_CORE_RUSTBUFFER_ALLOC
RustBuffer ffi_IrisCore_rustbuffer_alloc(uint64_t size, RustCallStatus *_Nonnull out_status
);
#endif
#ifndef UNIFFI_FFIDEF_FFI_IRIS_CORE_RUSTBUFFER_FROM_BYTES
#define UNIFFI_FFIDEF_FFI_IRIS_CORE_RUSTBUFFER_FROM_BYTES
RustBuffer ffi_IrisCore_rustbuffer_from_bytes(ForeignBytes bytes, RustCallStatus *_Nonnull out_status
);
#endif
#ifndef UNIFFI_FFIDEF_FFI_IRIS_CORE_RUSTBUFFER_FREE
#define UNIFFI_FFIDEF_FFI_IRIS_CORE_RUSTBUFFER_FREE
void ffi_IrisCore_rustbuffer_free(RustBuffer buf, RustCallStatus *_Nonnull out_status
);
#endif
#ifndef UNIFFI_FFIDEF_FFI_IRIS_CORE_RUSTBUFFER_RESERVE
#define UNIFFI_FFIDEF_FFI_IRIS_CORE_RUSTBUFFER_RESERVE
RustBuffer ffi_IrisCore_rustbuffer_reserve(RustBuffer buf, uint64_t additional, RustCallStatus *_Nonnull out_status
);
#endif
#ifndef UNIFFI_FFIDEF_FFI_IRIS_CORE_RUST_FUTURE_POLL_U8
#define UNIFFI_FFIDEF_FFI_IRIS_CORE_RUST_FUTURE_POLL_U8
void ffi_IrisCore_rust_future_poll_u8(uint64_t handle, UniffiRustFutureContinuationCallback _Nonnull callback, uint64_t callback_data
);
#endif
#ifndef UNIFFI_FFIDEF_FFI_IRIS_CORE_RUST_FUTURE_CANCEL_U8
#define UNIFFI_FFIDEF_FFI_IRIS_CORE_RUST_FUTURE_CANCEL_U8
void ffi_IrisCore_rust_future_cancel_u8(uint64_t handle
);
#endif
#ifndef UNIFFI_FFIDEF_FFI_IRIS_CORE_RUST_FUTURE_FREE_U8
#define UNIFFI_FFIDEF_FFI_IRIS_CORE_RUST_FUTURE_FREE_U8
void ffi_IrisCore_rust_future_free_u8(uint64_t handle
);
#endif
#ifndef UNIFFI_FFIDEF_FFI_IRIS_CORE_RUST_FUTURE_COMPLETE_U8
#define UNIFFI_FFIDEF_FFI_IRIS_CORE_RUST_FUTURE_COMPLETE_U8
uint8_t ffi_IrisCore_rust_future_complete_u8(uint64_t handle, RustCallStatus *_Nonnull out_status
);
#endif
#ifndef UNIFFI_FFIDEF_FFI_IRIS_CORE_RUST_FUTURE_POLL_I8
#define UNIFFI_FFIDEF_FFI_IRIS_CORE_RUST_FUTURE_POLL_I8
void ffi_IrisCore_rust_future_poll_i8(uint64_t handle, UniffiRustFutureContinuationCallback _Nonnull callback, uint64_t callback_data
);
#endif
#ifndef UNIFFI_FFIDEF_FFI_IRIS_CORE_RUST_FUTURE_CANCEL_I8
#define UNIFFI_FFIDEF_FFI_IRIS_CORE_RUST_FUTURE_CANCEL_I8
void ffi_IrisCore_rust_future_cancel_i8(uint64_t handle
);
#endif
#ifndef UNIFFI_FFIDEF_FFI_IRIS_CORE_RUST_FUTURE_FREE_I8
#define UNIFFI_FFIDEF_FFI_IRIS_CORE_RUST_FUTURE_FREE_I8
void ffi_IrisCore_rust_future_free_i8(uint64_t handle
);
#endif
#ifndef UNIFFI_FFIDEF_FFI_IRIS_CORE_RUST_FUTURE_COMPLETE_I8
#define UNIFFI_FFIDEF_FFI_IRIS_CORE_RUST_FUTURE_COMPLETE_I8
int8_t ffi_IrisCore_rust_future_complete_i8(uint64_t handle, RustCallStatus *_Nonnull out_status
);
#endif
#ifndef UNIFFI_FFIDEF_FFI_IRIS_CORE_RUST_FUTURE_POLL_U16
#define UNIFFI_FFIDEF_FFI_IRIS_CORE_RUST_FUTURE_POLL_U16
void ffi_IrisCore_rust_future_poll_u16(uint64_t handle, UniffiRustFutureContinuationCallback _Nonnull callback, uint64_t callback_data
);
#endif
#ifndef UNIFFI_FFIDEF_FFI_IRIS_CORE_RUST_FUTURE_CANCEL_U16
#define UNIFFI_FFIDEF_FFI_IRIS_CORE_RUST_FUTURE_CANCEL_U16
void ffi_IrisCore_rust_future_cancel_u16(uint64_t handle
);
#endif
#ifndef UNIFFI_FFIDEF_FFI_IRIS_CORE_RUST_FUTURE_FREE_U16
#define UNIFFI_FFIDEF_FFI_IRIS_CORE_RUST_FUTURE_FREE_U16
void ffi_IrisCore_rust_future_free_u16(uint64_t handle
);
#endif
#ifndef UNIFFI_FFIDEF_FFI_IRIS_CORE_RUST_FUTURE_COMPLETE_U16
#define UNIFFI_FFIDEF_FFI_IRIS_CORE_RUST_FUTURE_COMPLETE_U16
uint16_t ffi_IrisCore_rust_future_complete_u16(uint64_t handle, RustCallStatus *_Nonnull out_status
);
#endif
#ifndef UNIFFI_FFIDEF_FFI_IRIS_CORE_RUST_FUTURE_POLL_I16
#define UNIFFI_FFIDEF_FFI_IRIS_CORE_RUST_FUTURE_POLL_I16
void ffi_IrisCore_rust_future_poll_i16(uint64_t handle, UniffiRustFutureContinuationCallback _Nonnull callback, uint64_t callback_data
);
#endif
#ifndef UNIFFI_FFIDEF_FFI_IRIS_CORE_RUST_FUTURE_CANCEL_I16
#define UNIFFI_FFIDEF_FFI_IRIS_CORE_RUST_FUTURE_CANCEL_I16
void ffi_IrisCore_rust_future_cancel_i16(uint64_t handle
);
#endif
#ifndef UNIFFI_FFIDEF_FFI_IRIS_CORE_RUST_FUTURE_FREE_I16
#define UNIFFI_FFIDEF_FFI_IRIS_CORE_RUST_FUTURE_FREE_I16
void ffi_IrisCore_rust_future_free_i16(uint64_t handle
);
#endif
#ifndef UNIFFI_FFIDEF_FFI_IRIS_CORE_RUST_FUTURE_COMPLETE_I16
#define UNIFFI_FFIDEF_FFI_IRIS_CORE_RUST_FUTURE_COMPLETE_I16
int16_t ffi_IrisCore_rust_future_complete_i16(uint64_t handle, RustCallStatus *_Nonnull out_status
);
#endif
#ifndef UNIFFI_FFIDEF_FFI_IRIS_CORE_RUST_FUTURE_POLL_U32
#define UNIFFI_FFIDEF_FFI_IRIS_CORE_RUST_FUTURE_POLL_U32
void ffi_IrisCore_rust_future_poll_u32(uint64_t handle, UniffiRustFutureContinuationCallback _Nonnull callback, uint64_t callback_data
);
#endif
#ifndef UNIFFI_FFIDEF_FFI_IRIS_CORE_RUST_FUTURE_CANCEL_U32
#define UNIFFI_FFIDEF_FFI_IRIS_CORE_RUST_FUTURE_CANCEL_U32
void ffi_IrisCore_rust_future_cancel_u32(uint64_t handle
);
#endif
#ifndef UNIFFI_FFIDEF_FFI_IRIS_CORE_RUST_FUTURE_FREE_U32
#define UNIFFI_FFIDEF_FFI_IRIS_CORE_RUST_FUTURE_FREE_U32
void ffi_IrisCore_rust_future_free_u32(uint64_t handle
);
#endif
#ifndef UNIFFI_FFIDEF_FFI_IRIS_CORE_RUST_FUTURE_COMPLETE_U32
#define UNIFFI_FFIDEF_FFI_IRIS_CORE_RUST_FUTURE_COMPLETE_U32
uint32_t ffi_IrisCore_rust_future_complete_u32(uint64_t handle, RustCallStatus *_Nonnull out_status
);
#endif
#ifndef UNIFFI_FFIDEF_FFI_IRIS_CORE_RUST_FUTURE_POLL_I32
#define UNIFFI_FFIDEF_FFI_IRIS_CORE_RUST_FUTURE_POLL_I32
void ffi_IrisCore_rust_future_poll_i32(uint64_t handle, UniffiRustFutureContinuationCallback _Nonnull callback, uint64_t callback_data
);
#endif
#ifndef UNIFFI_FFIDEF_FFI_IRIS_CORE_RUST_FUTURE_CANCEL_I32
#define UNIFFI_FFIDEF_FFI_IRIS_CORE_RUST_FUTURE_CANCEL_I32
void ffi_IrisCore_rust_future_cancel_i32(uint64_t handle
);
#endif
#ifndef UNIFFI_FFIDEF_FFI_IRIS_CORE_RUST_FUTURE_FREE_I32
#define UNIFFI_FFIDEF_FFI_IRIS_CORE_RUST_FUTURE_FREE_I32
void ffi_IrisCore_rust_future_free_i32(uint64_t handle
);
#endif
#ifndef UNIFFI_FFIDEF_FFI_IRIS_CORE_RUST_FUTURE_COMPLETE_I32
#define UNIFFI_FFIDEF_FFI_IRIS_CORE_RUST_FUTURE_COMPLETE_I32
int32_t ffi_IrisCore_rust_future_complete_i32(uint64_t handle, RustCallStatus *_Nonnull out_status
);
#endif
#ifndef UNIFFI_FFIDEF_FFI_IRIS_CORE_RUST_FUTURE_POLL_U64
#define UNIFFI_FFIDEF_FFI_IRIS_CORE_RUST_FUTURE_POLL_U64
void ffi_IrisCore_rust_future_poll_u64(uint64_t handle, UniffiRustFutureContinuationCallback _Nonnull callback, uint64_t callback_data
);
#endif
#ifndef UNIFFI_FFIDEF_FFI_IRIS_CORE_RUST_FUTURE_CANCEL_U64
#define UNIFFI_FFIDEF_FFI_IRIS_CORE_RUST_FUTURE_CANCEL_U64
void ffi_IrisCore_rust_future_cancel_u64(uint64_t handle
);
#endif
#ifndef UNIFFI_FFIDEF_FFI_IRIS_CORE_RUST_FUTURE_FREE_U64
#define UNIFFI_FFIDEF_FFI_IRIS_CORE_RUST_FUTURE_FREE_U64
void ffi_IrisCore_rust_future_free_u64(uint64_t handle
);
#endif
#ifndef UNIFFI_FFIDEF_FFI_IRIS_CORE_RUST_FUTURE_COMPLETE_U64
#define UNIFFI_FFIDEF_FFI_IRIS_CORE_RUST_FUTURE_COMPLETE_U64
uint64_t ffi_IrisCore_rust_future_complete_u64(uint64_t handle, RustCallStatus *_Nonnull out_status
);
#endif
#ifndef UNIFFI_FFIDEF_FFI_IRIS_CORE_RUST_FUTURE_POLL_I64
#define UNIFFI_FFIDEF_FFI_IRIS_CORE_RUST_FUTURE_POLL_I64
void ffi_IrisCore_rust_future_poll_i64(uint64_t handle, UniffiRustFutureContinuationCallback _Nonnull callback, uint64_t callback_data
);
#endif
#ifndef UNIFFI_FFIDEF_FFI_IRIS_CORE_RUST_FUTURE_CANCEL_I64
#define UNIFFI_FFIDEF_FFI_IRIS_CORE_RUST_FUTURE_CANCEL_I64
void ffi_IrisCore_rust_future_cancel_i64(uint64_t handle
);
#endif
#ifndef UNIFFI_FFIDEF_FFI_IRIS_CORE_RUST_FUTURE_FREE_I64
#define UNIFFI_FFIDEF_FFI_IRIS_CORE_RUST_FUTURE_FREE_I64
void ffi_IrisCore_rust_future_free_i64(uint64_t handle
);
#endif
#ifndef UNIFFI_FFIDEF_FFI_IRIS_CORE_RUST_FUTURE_COMPLETE_I64
#define UNIFFI_FFIDEF_FFI_IRIS_CORE_RUST_FUTURE_COMPLETE_I64
int64_t ffi_IrisCore_rust_future_complete_i64(uint64_t handle, RustCallStatus *_Nonnull out_status
);
#endif
#ifndef UNIFFI_FFIDEF_FFI_IRIS_CORE_RUST_FUTURE_POLL_F32
#define UNIFFI_FFIDEF_FFI_IRIS_CORE_RUST_FUTURE_POLL_F32
void ffi_IrisCore_rust_future_poll_f32(uint64_t handle, UniffiRustFutureContinuationCallback _Nonnull callback, uint64_t callback_data
);
#endif
#ifndef UNIFFI_FFIDEF_FFI_IRIS_CORE_RUST_FUTURE_CANCEL_F32
#define UNIFFI_FFIDEF_FFI_IRIS_CORE_RUST_FUTURE_CANCEL_F32
void ffi_IrisCore_rust_future_cancel_f32(uint64_t handle
);
#endif
#ifndef UNIFFI_FFIDEF_FFI_IRIS_CORE_RUST_FUTURE_FREE_F32
#define UNIFFI_FFIDEF_FFI_IRIS_CORE_RUST_FUTURE_FREE_F32
void ffi_IrisCore_rust_future_free_f32(uint64_t handle
);
#endif
#ifndef UNIFFI_FFIDEF_FFI_IRIS_CORE_RUST_FUTURE_COMPLETE_F32
#define UNIFFI_FFIDEF_FFI_IRIS_CORE_RUST_FUTURE_COMPLETE_F32
float ffi_IrisCore_rust_future_complete_f32(uint64_t handle, RustCallStatus *_Nonnull out_status
);
#endif
#ifndef UNIFFI_FFIDEF_FFI_IRIS_CORE_RUST_FUTURE_POLL_F64
#define UNIFFI_FFIDEF_FFI_IRIS_CORE_RUST_FUTURE_POLL_F64
void ffi_IrisCore_rust_future_poll_f64(uint64_t handle, UniffiRustFutureContinuationCallback _Nonnull callback, uint64_t callback_data
);
#endif
#ifndef UNIFFI_FFIDEF_FFI_IRIS_CORE_RUST_FUTURE_CANCEL_F64
#define UNIFFI_FFIDEF_FFI_IRIS_CORE_RUST_FUTURE_CANCEL_F64
void ffi_IrisCore_rust_future_cancel_f64(uint64_t handle
);
#endif
#ifndef UNIFFI_FFIDEF_FFI_IRIS_CORE_RUST_FUTURE_FREE_F64
#define UNIFFI_FFIDEF_FFI_IRIS_CORE_RUST_FUTURE_FREE_F64
void ffi_IrisCore_rust_future_free_f64(uint64_t handle
);
#endif
#ifndef UNIFFI_FFIDEF_FFI_IRIS_CORE_RUST_FUTURE_COMPLETE_F64
#define UNIFFI_FFIDEF_FFI_IRIS_CORE_RUST_FUTURE_COMPLETE_F64
double ffi_IrisCore_rust_future_complete_f64(uint64_t handle, RustCallStatus *_Nonnull out_status
);
#endif
#ifndef UNIFFI_FFIDEF_FFI_IRIS_CORE_RUST_FUTURE_POLL_RUST_BUFFER
#define UNIFFI_FFIDEF_FFI_IRIS_CORE_RUST_FUTURE_POLL_RUST_BUFFER
void ffi_IrisCore_rust_future_poll_rust_buffer(uint64_t handle, UniffiRustFutureContinuationCallback _Nonnull callback, uint64_t callback_data
);
#endif
#ifndef UNIFFI_FFIDEF_FFI_IRIS_CORE_RUST_FUTURE_CANCEL_RUST_BUFFER
#define UNIFFI_FFIDEF_FFI_IRIS_CORE_RUST_FUTURE_CANCEL_RUST_BUFFER
void ffi_IrisCore_rust_future_cancel_rust_buffer(uint64_t handle
);
#endif
#ifndef UNIFFI_FFIDEF_FFI_IRIS_CORE_RUST_FUTURE_FREE_RUST_BUFFER
#define UNIFFI_FFIDEF_FFI_IRIS_CORE_RUST_FUTURE_FREE_RUST_BUFFER
void ffi_IrisCore_rust_future_free_rust_buffer(uint64_t handle
);
#endif
#ifndef UNIFFI_FFIDEF_FFI_IRIS_CORE_RUST_FUTURE_COMPLETE_RUST_BUFFER
#define UNIFFI_FFIDEF_FFI_IRIS_CORE_RUST_FUTURE_COMPLETE_RUST_BUFFER
RustBuffer ffi_IrisCore_rust_future_complete_rust_buffer(uint64_t handle, RustCallStatus *_Nonnull out_status
);
#endif
#ifndef UNIFFI_FFIDEF_FFI_IRIS_CORE_RUST_FUTURE_POLL_VOID
#define UNIFFI_FFIDEF_FFI_IRIS_CORE_RUST_FUTURE_POLL_VOID
void ffi_IrisCore_rust_future_poll_void(uint64_t handle, UniffiRustFutureContinuationCallback _Nonnull callback, uint64_t callback_data
);
#endif
#ifndef UNIFFI_FFIDEF_FFI_IRIS_CORE_RUST_FUTURE_CANCEL_VOID
#define UNIFFI_FFIDEF_FFI_IRIS_CORE_RUST_FUTURE_CANCEL_VOID
void ffi_IrisCore_rust_future_cancel_void(uint64_t handle
);
#endif
#ifndef UNIFFI_FFIDEF_FFI_IRIS_CORE_RUST_FUTURE_FREE_VOID
#define UNIFFI_FFIDEF_FFI_IRIS_CORE_RUST_FUTURE_FREE_VOID
void ffi_IrisCore_rust_future_free_void(uint64_t handle
);
#endif
#ifndef UNIFFI_FFIDEF_FFI_IRIS_CORE_RUST_FUTURE_COMPLETE_VOID
#define UNIFFI_FFIDEF_FFI_IRIS_CORE_RUST_FUTURE_COMPLETE_VOID
void ffi_IrisCore_rust_future_complete_void(uint64_t handle, RustCallStatus *_Nonnull out_status
);
#endif
#ifndef UNIFFI_FFIDEF_UNIFFI_IRIS_CORE_CHECKSUM_METHOD_FFIINBOXLISTENER_ON_MESSAGE
#define UNIFFI_FFIDEF_UNIFFI_IRIS_CORE_CHECKSUM_METHOD_FFIINBOXLISTENER_ON_MESSAGE
uint16_t uniffi_IrisCore_checksum_method_ffiinboxlistener_on_message(void
    
);
#endif
#ifndef UNIFFI_FFIDEF_UNIFFI_IRIS_CORE_CHECKSUM_METHOD_IRISENGINE_NODE_ID
#define UNIFFI_FFIDEF_UNIFFI_IRIS_CORE_CHECKSUM_METHOD_IRISENGINE_NODE_ID
uint16_t uniffi_IrisCore_checksum_method_irisengine_node_id(void
    
);
#endif
#ifndef UNIFFI_FFIDEF_UNIFFI_IRIS_CORE_CHECKSUM_METHOD_IRISENGINE_SEND_TEXT
#define UNIFFI_FFIDEF_UNIFFI_IRIS_CORE_CHECKSUM_METHOD_IRISENGINE_SEND_TEXT
uint16_t uniffi_IrisCore_checksum_method_irisengine_send_text(void
    
);
#endif
#ifndef UNIFFI_FFIDEF_UNIFFI_IRIS_CORE_CHECKSUM_METHOD_IRISENGINE_SET_BODY_RENDERER
#define UNIFFI_FFIDEF_UNIFFI_IRIS_CORE_CHECKSUM_METHOD_IRISENGINE_SET_BODY_RENDERER
uint16_t uniffi_IrisCore_checksum_method_irisengine_set_body_renderer(void
    
);
#endif
#ifndef UNIFFI_FFIDEF_UNIFFI_IRIS_CORE_CHECKSUM_METHOD_IRISENGINE_START_ALL
#define UNIFFI_FFIDEF_UNIFFI_IRIS_CORE_CHECKSUM_METHOD_IRISENGINE_START_ALL
uint16_t uniffi_IrisCore_checksum_method_irisengine_start_all(void
    
);
#endif
#ifndef UNIFFI_FFIDEF_UNIFFI_IRIS_CORE_CHECKSUM_METHOD_IRISENGINE_STOP_ALL
#define UNIFFI_FFIDEF_UNIFFI_IRIS_CORE_CHECKSUM_METHOD_IRISENGINE_STOP_ALL
uint16_t uniffi_IrisCore_checksum_method_irisengine_stop_all(void
    
);
#endif
#ifndef UNIFFI_FFIDEF_UNIFFI_IRIS_CORE_CHECKSUM_METHOD_IRISENGINE_SUBSCRIBE_INBOX
#define UNIFFI_FFIDEF_UNIFFI_IRIS_CORE_CHECKSUM_METHOD_IRISENGINE_SUBSCRIBE_INBOX
uint16_t uniffi_IrisCore_checksum_method_irisengine_subscribe_inbox(void
    
);
#endif
#ifndef UNIFFI_FFIDEF_UNIFFI_IRIS_CORE_CHECKSUM_METHOD_FFIBLEADAPTER_START_SCAN
#define UNIFFI_FFIDEF_UNIFFI_IRIS_CORE_CHECKSUM_METHOD_FFIBLEADAPTER_START_SCAN
uint16_t uniffi_IrisCore_checksum_method_ffibleadapter_start_scan(void
    
);
#endif
#ifndef UNIFFI_FFIDEF_UNIFFI_IRIS_CORE_CHECKSUM_METHOD_FFIBLEADAPTER_STOP_SCAN
#define UNIFFI_FFIDEF_UNIFFI_IRIS_CORE_CHECKSUM_METHOD_FFIBLEADAPTER_STOP_SCAN
uint16_t uniffi_IrisCore_checksum_method_ffibleadapter_stop_scan(void
    
);
#endif
#ifndef UNIFFI_FFIDEF_UNIFFI_IRIS_CORE_CHECKSUM_METHOD_FFIBLEADAPTER_START_ADVERTISING
#define UNIFFI_FFIDEF_UNIFFI_IRIS_CORE_CHECKSUM_METHOD_FFIBLEADAPTER_START_ADVERTISING
uint16_t uniffi_IrisCore_checksum_method_ffibleadapter_start_advertising(void
    
);
#endif
#ifndef UNIFFI_FFIDEF_UNIFFI_IRIS_CORE_CHECKSUM_METHOD_FFIBLEADAPTER_STOP_ADVERTISING
#define UNIFFI_FFIDEF_UNIFFI_IRIS_CORE_CHECKSUM_METHOD_FFIBLEADAPTER_STOP_ADVERTISING
uint16_t uniffi_IrisCore_checksum_method_ffibleadapter_stop_advertising(void
    
);
#endif
#ifndef UNIFFI_FFIDEF_UNIFFI_IRIS_CORE_CHECKSUM_METHOD_FFIBLEADAPTER_CONNECT_GATT
#define UNIFFI_FFIDEF_UNIFFI_IRIS_CORE_CHECKSUM_METHOD_FFIBLEADAPTER_CONNECT_GATT
uint16_t uniffi_IrisCore_checksum_method_ffibleadapter_connect_gatt(void
    
);
#endif
#ifndef UNIFFI_FFIDEF_UNIFFI_IRIS_CORE_CHECKSUM_METHOD_FFIBLEADAPTER_DISCONNECT_GATT
#define UNIFFI_FFIDEF_UNIFFI_IRIS_CORE_CHECKSUM_METHOD_FFIBLEADAPTER_DISCONNECT_GATT
uint16_t uniffi_IrisCore_checksum_method_ffibleadapter_disconnect_gatt(void
    
);
#endif
#ifndef UNIFFI_FFIDEF_UNIFFI_IRIS_CORE_CHECKSUM_METHOD_FFIBLEADAPTER_GATT_WRITE
#define UNIFFI_FFIDEF_UNIFFI_IRIS_CORE_CHECKSUM_METHOD_FFIBLEADAPTER_GATT_WRITE
uint16_t uniffi_IrisCore_checksum_method_ffibleadapter_gatt_write(void
    
);
#endif
#ifndef UNIFFI_FFIDEF_UNIFFI_IRIS_CORE_CHECKSUM_METHOD_FFIBLEADAPTER_GATT_READ
#define UNIFFI_FFIDEF_UNIFFI_IRIS_CORE_CHECKSUM_METHOD_FFIBLEADAPTER_GATT_READ
uint16_t uniffi_IrisCore_checksum_method_ffibleadapter_gatt_read(void
    
);
#endif
#ifndef UNIFFI_FFIDEF_UNIFFI_IRIS_CORE_CHECKSUM_METHOD_FFIBLEADAPTER_SET_MTU
#define UNIFFI_FFIDEF_UNIFFI_IRIS_CORE_CHECKSUM_METHOD_FFIBLEADAPTER_SET_MTU
uint16_t uniffi_IrisCore_checksum_method_ffibleadapter_set_mtu(void
    
);
#endif
#ifndef UNIFFI_FFIDEF_UNIFFI_IRIS_CORE_CHECKSUM_METHOD_FFIBLEADAPTER_INCOMING_GATT_WRITES
#define UNIFFI_FFIDEF_UNIFFI_IRIS_CORE_CHECKSUM_METHOD_FFIBLEADAPTER_INCOMING_GATT_WRITES
uint16_t uniffi_IrisCore_checksum_method_ffibleadapter_incoming_gatt_writes(void
    
);
#endif
#ifndef UNIFFI_FFIDEF_UNIFFI_IRIS_CORE_CHECKSUM_METHOD_FFIBLEADAPTER_SCAN_RESULTS
#define UNIFFI_FFIDEF_UNIFFI_IRIS_CORE_CHECKSUM_METHOD_FFIBLEADAPTER_SCAN_RESULTS
uint16_t uniffi_IrisCore_checksum_method_ffibleadapter_scan_results(void
    
);
#endif
#ifndef UNIFFI_FFIDEF_UNIFFI_IRIS_CORE_CHECKSUM_METHOD_IRISBODY_SUMMARIZE
#define UNIFFI_FFIDEF_UNIFFI_IRIS_CORE_CHECKSUM_METHOD_IRISBODY_SUMMARIZE
uint16_t uniffi_IrisCore_checksum_method_irisbody_summarize(void
    
);
#endif
#ifndef UNIFFI_FFIDEF_UNIFFI_IRIS_CORE_CHECKSUM_METHOD_IRISBODY_DESCRIBE
#define UNIFFI_FFIDEF_UNIFFI_IRIS_CORE_CHECKSUM_METHOD_IRISBODY_DESCRIBE
uint16_t uniffi_IrisCore_checksum_method_irisbody_describe(void
    
);
#endif
#ifndef UNIFFI_FFIDEF_UNIFFI_IRIS_CORE_CHECKSUM_CONSTRUCTOR_IRISENGINE_NEW
#define UNIFFI_FFIDEF_UNIFFI_IRIS_CORE_CHECKSUM_CONSTRUCTOR_IRISENGINE_NEW
uint16_t uniffi_IrisCore_checksum_constructor_irisengine_new(void
    
);
#endif
#ifndef UNIFFI_FFIDEF_FFI_IRIS_CORE_UNIFFI_CONTRACT_VERSION
#define UNIFFI_FFIDEF_FFI_IRIS_CORE_UNIFFI_CONTRACT_VERSION
uint32_t ffi_IrisCore_uniffi_contract_version(void
    
);
#endif

