// This file was autogenerated by some hot garbage in the `uniffi` crate.
// Trust me, you don't want to mess with it!

// swiftlint:disable all
import Foundation

// Depending on the consumer's build setup, the low-level FFI code
// might be in a separate module, or it might be compiled inline into
// this module. This is a bit of light hackery to work with both.
#if canImport(IrisCoreFFI)
import IrisCoreFFI
#endif

fileprivate extension RustBuffer {
    // Allocate a new buffer, copying the contents of a `UInt8` array.
    init(bytes: [UInt8]) {
        let rbuf = bytes.withUnsafeBufferPointer { ptr in
            RustBuffer.from(ptr)
        }
        self.init(capacity: rbuf.capacity, len: rbuf.len, data: rbuf.data)
    }

    static func empty() -> RustBuffer {
        RustBuffer(capacity: 0, len:0, data: nil)
    }

    static func from(_ ptr: UnsafeBufferPointer<UInt8>) -> RustBuffer {
        try! rustCall { ffi_IrisCore_rustbuffer_from_bytes(ForeignBytes(bufferPointer: ptr), $0) }
    }

    // Frees the buffer in place.
    // The buffer must not be used after this is called.
    func deallocate() {
        try! rustCall { ffi_IrisCore_rustbuffer_free(self, $0) }
    }
}

fileprivate extension ForeignBytes {
    init(bufferPointer: UnsafeBufferPointer<UInt8>) {
        self.init(len: Int32(bufferPointer.count), data: bufferPointer.baseAddress)
    }
}

// For every type used in the interface, we provide helper methods for conveniently
// lifting and lowering that type from C-compatible data, and for reading and writing
// values of that type in a buffer.

// Helper classes/extensions that don't change.
// Someday, this will be in a library of its own.

fileprivate extension Data {
    init(rustBuffer: RustBuffer) {
        self.init(
            bytesNoCopy: rustBuffer.data!,
            count: Int(rustBuffer.len),
            deallocator: .none
        )
    }
}

// Define reader functionality.  Normally this would be defined in a class or
// struct, but we use standalone functions instead in order to make external
// types work.
//
// With external types, one swift source file needs to be able to call the read
// method on another source file's FfiConverter, but then what visibility
// should Reader have?
// - If Reader is fileprivate, then this means the read() must also
//   be fileprivate, which doesn't work with external types.
// - If Reader is internal/public, we'll get compile errors since both source
//   files will try define the same type.
//
// Instead, the read() method and these helper functions input a tuple of data

fileprivate func createReader(data: Data) -> (data: Data, offset: Data.Index) {
    (data: data, offset: 0)
}

// Reads an integer at the current offset, in big-endian order, and advances
// the offset on success. Throws if reading the integer would move the
// offset past the end of the buffer.
fileprivate func readInt<T: FixedWidthInteger>(_ reader: inout (data: Data, offset: Data.Index)) throws -> T {
    let range = reader.offset..<reader.offset + MemoryLayout<T>.size
    guard reader.data.count >= range.upperBound else {
        throw UniffiInternalError.bufferOverflow
    }
    if T.self == UInt8.self {
        let value = reader.data[reader.offset]
        reader.offset += 1
        return value as! T
    }
    var value: T = 0
    let _ = withUnsafeMutableBytes(of: &value, { reader.data.copyBytes(to: $0, from: range)})
    reader.offset = range.upperBound
    return value.bigEndian
}

// Reads an arbitrary number of bytes, to be used to read
// raw bytes, this is useful when lifting strings
fileprivate func readBytes(_ reader: inout (data: Data, offset: Data.Index), count: Int) throws -> Array<UInt8> {
    let range = reader.offset..<(reader.offset+count)
    guard reader.data.count >= range.upperBound else {
        throw UniffiInternalError.bufferOverflow
    }
    var value = [UInt8](repeating: 0, count: count)
    value.withUnsafeMutableBufferPointer({ buffer in
        reader.data.copyBytes(to: buffer, from: range)
    })
    reader.offset = range.upperBound
    return value
}

// Reads a float at the current offset.
fileprivate func readFloat(_ reader: inout (data: Data, offset: Data.Index)) throws -> Float {
    return Float(bitPattern: try readInt(&reader))
}

// Reads a float at the current offset.
fileprivate func readDouble(_ reader: inout (data: Data, offset: Data.Index)) throws -> Double {
    return Double(bitPattern: try readInt(&reader))
}

// Indicates if the offset has reached the end of the buffer.
fileprivate func hasRemaining(_ reader: (data: Data, offset: Data.Index)) -> Bool {
    return reader.offset < reader.data.count
}

// Define writer functionality.  Normally this would be defined in a class or
// struct, but we use standalone functions instead in order to make external
// types work.  See the above discussion on Readers for details.

fileprivate func createWriter() -> [UInt8] {
    return []
}

fileprivate func writeBytes<S>(_ writer: inout [UInt8], _ byteArr: S) where S: Sequence, S.Element == UInt8 {
    writer.append(contentsOf: byteArr)
}

// Writes an integer in big-endian order.
//
// Warning: make sure what you are trying to write
// is in the correct type!
fileprivate func writeInt<T: FixedWidthInteger>(_ writer: inout [UInt8], _ value: T) {
    var value = value.bigEndian
    withUnsafeBytes(of: &value) { writer.append(contentsOf: $0) }
}

fileprivate func writeFloat(_ writer: inout [UInt8], _ value: Float) {
    writeInt(&writer, value.bitPattern)
}

fileprivate func writeDouble(_ writer: inout [UInt8], _ value: Double) {
    writeInt(&writer, value.bitPattern)
}

// Protocol for types that transfer other types across the FFI. This is
// analogous to the Rust trait of the same name.
fileprivate protocol FfiConverter {
    associatedtype FfiType
    associatedtype SwiftType

    static func lift(_ value: FfiType) throws -> SwiftType
    static func lower(_ value: SwiftType) -> FfiType
    static func read(from buf: inout (data: Data, offset: Data.Index)) throws -> SwiftType
    static func write(_ value: SwiftType, into buf: inout [UInt8])
}

// Types conforming to `Primitive` pass themselves directly over the FFI.
fileprivate protocol FfiConverterPrimitive: FfiConverter where FfiType == SwiftType { }

extension FfiConverterPrimitive {
#if swift(>=5.8)
    @_documentation(visibility: private)
#endif
    public static func lift(_ value: FfiType) throws -> SwiftType {
        return value
    }

#if swift(>=5.8)
    @_documentation(visibility: private)
#endif
    public static func lower(_ value: SwiftType) -> FfiType {
        return value
    }
}

// Types conforming to `FfiConverterRustBuffer` lift and lower into a `RustBuffer`.
// Used for complex types where it's hard to write a custom lift/lower.
fileprivate protocol FfiConverterRustBuffer: FfiConverter where FfiType == RustBuffer {}

extension FfiConverterRustBuffer {
#if swift(>=5.8)
    @_documentation(visibility: private)
#endif
    public static func lift(_ buf: RustBuffer) throws -> SwiftType {
        var reader = createReader(data: Data(rustBuffer: buf))
        let value = try read(from: &reader)
        if hasRemaining(reader) {
            throw UniffiInternalError.incompleteData
        }
        buf.deallocate()
        return value
    }

#if swift(>=5.8)
    @_documentation(visibility: private)
#endif
    public static func lower(_ value: SwiftType) -> RustBuffer {
          var writer = createWriter()
          write(value, into: &writer)
          return RustBuffer(bytes: writer)
    }
}
// An error type for FFI errors. These errors occur at the UniFFI level, not
// the library level.
fileprivate enum UniffiInternalError: LocalizedError {
    case bufferOverflow
    case incompleteData
    case unexpectedOptionalTag
    case unexpectedEnumCase
    case unexpectedNullPointer
    case unexpectedRustCallStatusCode
    case unexpectedRustCallError
    case unexpectedStaleHandle
    case rustPanic(_ message: String)

    public var errorDescription: String? {
        switch self {
        case .bufferOverflow: return "Reading the requested value would read past the end of the buffer"
        case .incompleteData: return "The buffer still has data after lifting its containing value"
        case .unexpectedOptionalTag: return "Unexpected optional tag; should be 0 or 1"
        case .unexpectedEnumCase: return "Raw enum value doesn't match any cases"
        case .unexpectedNullPointer: return "Raw pointer value was null"
        case .unexpectedRustCallStatusCode: return "Unexpected RustCallStatus code"
        case .unexpectedRustCallError: return "CALL_ERROR but no errorClass specified"
        case .unexpectedStaleHandle: return "The object in the handle map has been dropped already"
        case let .rustPanic(message): return message
        }
    }
}

fileprivate extension NSLock {
    func withLock<T>(f: () throws -> T) rethrows -> T {
        self.lock()
        defer { self.unlock() }
        return try f()
    }
}

fileprivate let CALL_SUCCESS: Int8 = 0
fileprivate let CALL_ERROR: Int8 = 1
fileprivate let CALL_UNEXPECTED_ERROR: Int8 = 2
fileprivate let CALL_CANCELLED: Int8 = 3

fileprivate extension RustCallStatus {
    init() {
        self.init(
            code: CALL_SUCCESS,
            errorBuf: RustBuffer.init(
                capacity: 0,
                len: 0,
                data: nil
            )
        )
    }
}

private func rustCall<T>(_ callback: (UnsafeMutablePointer<RustCallStatus>) -> T) throws -> T {
    let neverThrow: ((RustBuffer) throws -> Never)? = nil
    return try makeRustCall(callback, errorHandler: neverThrow)
}

private func rustCallWithError<T, E: Swift.Error>(
    _ errorHandler: @escaping (RustBuffer) throws -> E,
    _ callback: (UnsafeMutablePointer<RustCallStatus>) -> T) throws -> T {
    try makeRustCall(callback, errorHandler: errorHandler)
}

private func makeRustCall<T, E: Swift.Error>(
    _ callback: (UnsafeMutablePointer<RustCallStatus>) -> T,
    errorHandler: ((RustBuffer) throws -> E)?
) throws -> T {
    uniffiEnsureIrisCoreInitialized()
    var callStatus = RustCallStatus.init()
    let returnedVal = callback(&callStatus)
    try uniffiCheckCallStatus(callStatus: callStatus, errorHandler: errorHandler)
    return returnedVal
}

private func uniffiCheckCallStatus<E: Swift.Error>(
    callStatus: RustCallStatus,
    errorHandler: ((RustBuffer) throws -> E)?
) throws {
    switch callStatus.code {
        case CALL_SUCCESS:
            return

        case CALL_ERROR:
            if let errorHandler = errorHandler {
                throw try errorHandler(callStatus.errorBuf)
            } else {
                callStatus.errorBuf.deallocate()
                throw UniffiInternalError.unexpectedRustCallError
            }

        case CALL_UNEXPECTED_ERROR:
            // When the rust code sees a panic, it tries to construct a RustBuffer
            // with the message.  But if that code panics, then it just sends back
            // an empty buffer.
            if callStatus.errorBuf.len > 0 {
                throw UniffiInternalError.rustPanic(try FfiConverterString.lift(callStatus.errorBuf))
            } else {
                callStatus.errorBuf.deallocate()
                throw UniffiInternalError.rustPanic("Rust panic")
            }

        case CALL_CANCELLED:
            fatalError("Cancellation not supported yet")

        default:
            throw UniffiInternalError.unexpectedRustCallStatusCode
    }
}

private func uniffiTraitInterfaceCall<T>(
    callStatus: UnsafeMutablePointer<RustCallStatus>,
    makeCall: () throws -> T,
    writeReturn: (T) -> ()
) {
    do {
        try writeReturn(makeCall())
    } catch let error {
        callStatus.pointee.code = CALL_UNEXPECTED_ERROR
        callStatus.pointee.errorBuf = FfiConverterString.lower(String(describing: error))
    }
}

private func uniffiTraitInterfaceCallWithError<T, E>(
    callStatus: UnsafeMutablePointer<RustCallStatus>,
    makeCall: () throws -> T,
    writeReturn: (T) -> (),
    lowerError: (E) -> RustBuffer
) {
    do {
        try writeReturn(makeCall())
    } catch let error as E {
        callStatus.pointee.code = CALL_ERROR
        callStatus.pointee.errorBuf = lowerError(error)
    } catch {
        callStatus.pointee.code = CALL_UNEXPECTED_ERROR
        callStatus.pointee.errorBuf = FfiConverterString.lower(String(describing: error))
    }
}
// Initial value and increment amount for handles. 
// These ensure that SWIFT handles always have the lowest bit set
fileprivate let UNIFFI_HANDLEMAP_INITIAL: UInt64 = 1
fileprivate let UNIFFI_HANDLEMAP_DELTA: UInt64 = 2

fileprivate final class UniffiHandleMap<T>: @unchecked Sendable {
    // All mutation happens with this lock held, which is why we implement @unchecked Sendable.
    private let lock = NSLock()
    private var map: [UInt64: T] = [:]
    private var currentHandle: UInt64 = UNIFFI_HANDLEMAP_INITIAL

    func insert(obj: T) -> UInt64 {
        lock.withLock {
            return doInsert(obj)
        }
    }

    // Low-level insert function, this assumes `lock` is held.
    private func doInsert(_ obj: T) -> UInt64 {
        let handle = currentHandle
        currentHandle += UNIFFI_HANDLEMAP_DELTA
        map[handle] = obj
        return handle
    }

     func get(handle: UInt64) throws -> T {
        try lock.withLock {
            guard let obj = map[handle] else {
                throw UniffiInternalError.unexpectedStaleHandle
            }
            return obj
        }
    }

     func clone(handle: UInt64) throws -> UInt64 {
        try lock.withLock {
            guard let obj = map[handle] else {
                throw UniffiInternalError.unexpectedStaleHandle
            }
            return doInsert(obj)
        }
    }

    @discardableResult
    func remove(handle: UInt64) throws -> T {
        try lock.withLock {
            guard let obj = map.removeValue(forKey: handle) else {
                throw UniffiInternalError.unexpectedStaleHandle
            }
            return obj
        }
    }

    var count: Int {
        // Bug #27: map.count must be read under the lock — concurrent insert/remove
        // from the Rust FFI thread causes a data race on the Dictionary.
        get { lock.withLock { map.count } }
    }
}


// Public interface members begin here.
// Magic number for the Rust proxy to call using the same mechanism as every other method,
// to free the callback once it's dropped by Rust.
private let IDX_CALLBACK_FREE: Int32 = 0
// Callback return codes
private let UNIFFI_CALLBACK_SUCCESS: Int32 = 0
private let UNIFFI_CALLBACK_ERROR: Int32 = 1
private let UNIFFI_CALLBACK_UNEXPECTED_ERROR: Int32 = 2

#if swift(>=5.8)
@_documentation(visibility: private)
#endif
fileprivate struct FfiConverterUInt8: FfiConverterPrimitive {
    typealias FfiType = UInt8
    typealias SwiftType = UInt8

    public static func read(from buf: inout (data: Data, offset: Data.Index)) throws -> UInt8 {
        return try lift(readInt(&buf))
    }

    public static func write(_ value: UInt8, into buf: inout [UInt8]) {
        writeInt(&buf, lower(value))
    }
}

#if swift(>=5.8)
@_documentation(visibility: private)
#endif
fileprivate struct FfiConverterUInt16: FfiConverterPrimitive {
    typealias FfiType = UInt16
    typealias SwiftType = UInt16

    public static func read(from buf: inout (data: Data, offset: Data.Index)) throws -> UInt16 {
        return try lift(readInt(&buf))
    }

    public static func write(_ value: SwiftType, into buf: inout [UInt8]) {
        writeInt(&buf, lower(value))
    }
}

#if swift(>=5.8)
@_documentation(visibility: private)
#endif
fileprivate struct FfiConverterInt32: FfiConverterPrimitive {
    typealias FfiType = Int32
    typealias SwiftType = Int32

    public static func read(from buf: inout (data: Data, offset: Data.Index)) throws -> Int32 {
        return try lift(readInt(&buf))
    }

    public static func write(_ value: Int32, into buf: inout [UInt8]) {
        writeInt(&buf, lower(value))
    }
}

#if swift(>=5.8)
@_documentation(visibility: private)
#endif
fileprivate struct FfiConverterUInt64: FfiConverterPrimitive {
    typealias FfiType = UInt64
    typealias SwiftType = UInt64

    public static func read(from buf: inout (data: Data, offset: Data.Index)) throws -> UInt64 {
        return try lift(readInt(&buf))
    }

    public static func write(_ value: SwiftType, into buf: inout [UInt8]) {
        writeInt(&buf, lower(value))
    }
}

#if swift(>=5.8)
@_documentation(visibility: private)
#endif
fileprivate struct FfiConverterBool : FfiConverter {
    typealias FfiType = Int8
    typealias SwiftType = Bool

    public static func lift(_ value: Int8) throws -> Bool {
        return value != 0
    }

    public static func lower(_ value: Bool) -> Int8 {
        return value ? 1 : 0
    }

    public static func read(from buf: inout (data: Data, offset: Data.Index)) throws -> Bool {
        return try lift(readInt(&buf))
    }

    public static func write(_ value: Bool, into buf: inout [UInt8]) {
        writeInt(&buf, lower(value))
    }
}

#if swift(>=5.8)
@_documentation(visibility: private)
#endif
fileprivate struct FfiConverterString: FfiConverter {
    typealias SwiftType = String
    typealias FfiType = RustBuffer

    public static func lift(_ value: RustBuffer) throws -> String {
        defer {
            value.deallocate()
        }
        if value.data == nil {
            return String()
        }
        let bytes = UnsafeBufferPointer<UInt8>(start: value.data!, count: Int(value.len))
        // Use Swift's native UTF-8 decoder; `String(bytes:encoding:.utf8)` goes
        // through Foundation's NSString and silently strips a leading U+FEFF BOM.
        // Invalid UTF-8 substitutes U+FFFD instead of trapping (unreachable
        // given Rust's `String` invariant).
        return String(decoding: bytes, as: UTF8.self)
    }

    public static func lower(_ value: String) -> RustBuffer {
        return value.utf8CString.withUnsafeBufferPointer { ptr in
            // The swift string gives us int8_t, we want uint8_t.
            ptr.withMemoryRebound(to: UInt8.self) { ptr in
                // The swift string gives us a trailing null byte, we don't want it.
                let buf = UnsafeBufferPointer(rebasing: ptr.prefix(upTo: ptr.count - 1))
                return RustBuffer.from(buf)
            }
        }
    }

    public static func read(from buf: inout (data: Data, offset: Data.Index)) throws -> String {
        let len: Int32 = try readInt(&buf)
        // See `lift` above for why we avoid Foundation's NSString-backed decoder here.
        return String(decoding: try readBytes(&buf, count: Int(len)), as: UTF8.self)
    }

    public static func write(_ value: String, into buf: inout [UInt8]) {
        let len = Int32(value.utf8.count)
        writeInt(&buf, len)
        writeBytes(&buf, value.utf8)
    }
}

#if swift(>=5.8)
@_documentation(visibility: private)
#endif
fileprivate struct FfiConverterData: FfiConverterRustBuffer {
    typealias SwiftType = Data

    public static func read(from buf: inout (data: Data, offset: Data.Index)) throws -> Data {
        let len: Int32 = try readInt(&buf)
        return Data(try readBytes(&buf, count: Int(len)))
    }

    public static func write(_ value: Data, into buf: inout [UInt8]) {
        let len = Int32(value.count)
        writeInt(&buf, len)
        writeBytes(&buf, value)
    }
}




/**
 * Foreign-trait projection of `ble::BleAdapter` (11-op iOS contract).
 * Implemented by `IosBleAdapter` (Swift/CoreBluetooth); simulated in Rust
 * unit tests. `start_advertising` drops service data at the FFI boundary on
 * iOS (the wire carries only local name + service UUIDs).
 */
public protocol FfiBleAdapter: AnyObject, Sendable {
    
    func startScan(filter: FfiScanFilter) throws  -> UInt64
    
    func stopScan(handle: UInt64) 
    
    func startAdvertising(data: FfiAdvertisementData) throws  -> UInt64
    
    func stopAdvertising(handle: UInt64) 
    
    func connectGatt(address: String) throws  -> UInt64
    
    func disconnectGatt(handle: UInt64) 
    
    func gattWrite(handle: UInt64, charUuid: String, data: Data) throws 
    
    /**
     * Connect-to-identify read (DEC-BLE-002-0015 / IOS_DESIGN §4): fetch the
     * peer's discovery beacon from `IRIS_IDENTIFY_CHARACTERISTIC` ->
     * `DiscoveryBeacon::parse` -> candidate peer. BLE-RT-C003 timeout is
     * enforced by the Swift side and surfaced as `IrisFfiError::Timeout`.
     */
    func gattRead(handle: UInt64, charUuid: String) throws  -> Data
    
    /**
     * No-op request returning `maximumWriteValueLength(for: .withResponse)`
     * (negotiated ATT payload, cap 512; AC-8).
     */
    func setMtu(handle: UInt64, mtu: UInt16) throws  -> UInt16
    
    /**
     * Drain inbound GATT writes (projection of the MutexGuard drain).
     */
    func incomingGattWrites()  -> [FfiGattWriteEvent]
    
    /**
     * Drain scan results (projection of the MutexGuard drain).
     */
    func scanResults()  -> [FfiScanResult]
    
}
/**
 * Foreign-trait projection of `ble::BleAdapter` (11-op iOS contract).
 * Implemented by `IosBleAdapter` (Swift/CoreBluetooth); simulated in Rust
 * unit tests. `start_advertising` drops service data at the FFI boundary on
 * iOS (the wire carries only local name + service UUIDs).
 */
open class FfiBleAdapterImpl: FfiBleAdapter, @unchecked Sendable {
    fileprivate let handle: UInt64

    /// Used to instantiate a [FFIObject] without an actual handle, for fakes in tests, mostly.
#if swift(>=5.8)
    @_documentation(visibility: private)
#endif
    public struct NoHandle {
        public init() {}
    }

    // TODO: We'd like this to be `private` but for Swifty reasons,
    // we can't implement `FfiConverter` without making this `required` and we can't
    // make it `required` without making it `public`.
#if swift(>=5.8)
    @_documentation(visibility: private)
#endif
    required public init(unsafeFromHandle handle: UInt64) {
        self.handle = handle
    }

    // This constructor can be used to instantiate a fake object.
    // - Parameter noHandle: Placeholder value so we can have a constructor separate from the default empty one that may be implemented for classes extending [FFIObject].
    //
    // - Warning:
    //     Any object instantiated with this constructor cannot be passed to an actual Rust-backed object. Since there isn't a backing handle the FFI lower functions will crash.
#if swift(>=5.8)
    @_documentation(visibility: private)
#endif
    public init(noHandle: NoHandle) {
        self.handle = 0
    }

#if swift(>=5.8)
    @_documentation(visibility: private)
#endif
    public func uniffiCloneHandle() -> UInt64 {
        return try! rustCall { uniffi_IrisCore_fn_clone_ffibleadapter(self.handle, $0) }
    }
    // No primary constructor declared for this class.

    deinit {
        if handle == 0 {
            // Mock objects have handle=0 don't try to free them
            return
        }

        try! rustCall { uniffi_IrisCore_fn_free_ffibleadapter(handle, $0) }
    }

    

    
open func startScan(filter: FfiScanFilter)throws  -> UInt64  {
    return try  FfiConverterUInt64.lift(try rustCallWithError(FfiConverterTypeIrisFfiError_lift) {
    uniffi_IrisCore_fn_method_ffibleadapter_start_scan(
            self.uniffiCloneHandle(),
        FfiConverterTypeFfiScanFilter_lower(filter),$0
    )
})
}
    
open func stopScan(handle: UInt64)  {try! rustCall() {
    uniffi_IrisCore_fn_method_ffibleadapter_stop_scan(
            self.uniffiCloneHandle(),
        FfiConverterUInt64.lower(handle),$0
    )
}
}
    
open func startAdvertising(data: FfiAdvertisementData)throws  -> UInt64  {
    return try  FfiConverterUInt64.lift(try rustCallWithError(FfiConverterTypeIrisFfiError_lift) {
    uniffi_IrisCore_fn_method_ffibleadapter_start_advertising(
            self.uniffiCloneHandle(),
        FfiConverterTypeFfiAdvertisementData_lower(data),$0
    )
})
}
    
open func stopAdvertising(handle: UInt64)  {try! rustCall() {
    uniffi_IrisCore_fn_method_ffibleadapter_stop_advertising(
            self.uniffiCloneHandle(),
        FfiConverterUInt64.lower(handle),$0
    )
}
}
    
open func connectGatt(address: String)throws  -> UInt64  {
    return try  FfiConverterUInt64.lift(try rustCallWithError(FfiConverterTypeIrisFfiError_lift) {
    uniffi_IrisCore_fn_method_ffibleadapter_connect_gatt(
            self.uniffiCloneHandle(),
        FfiConverterString.lower(address),$0
    )
})
}
    
open func disconnectGatt(handle: UInt64)  {try! rustCall() {
    uniffi_IrisCore_fn_method_ffibleadapter_disconnect_gatt(
            self.uniffiCloneHandle(),
        FfiConverterUInt64.lower(handle),$0
    )
}
}
    
open func gattWrite(handle: UInt64, charUuid: String, data: Data)throws   {try rustCallWithError(FfiConverterTypeIrisFfiError_lift) {
    uniffi_IrisCore_fn_method_ffibleadapter_gatt_write(
            self.uniffiCloneHandle(),
        FfiConverterUInt64.lower(handle),
        FfiConverterString.lower(charUuid),
        FfiConverterData.lower(data),$0
    )
}
}
    
    /**
     * Connect-to-identify read (DEC-BLE-002-0015 / IOS_DESIGN §4): fetch the
     * peer's discovery beacon from `IRIS_IDENTIFY_CHARACTERISTIC` ->
     * `DiscoveryBeacon::parse` -> candidate peer. BLE-RT-C003 timeout is
     * enforced by the Swift side and surfaced as `IrisFfiError::Timeout`.
     */
open func gattRead(handle: UInt64, charUuid: String)throws  -> Data  {
    return try  FfiConverterData.lift(try rustCallWithError(FfiConverterTypeIrisFfiError_lift) {
    uniffi_IrisCore_fn_method_ffibleadapter_gatt_read(
            self.uniffiCloneHandle(),
        FfiConverterUInt64.lower(handle),
        FfiConverterString.lower(charUuid),$0
    )
})
}
    
    /**
     * No-op request returning `maximumWriteValueLength(for: .withResponse)`
     * (negotiated ATT payload, cap 512; AC-8).
     */
open func setMtu(handle: UInt64, mtu: UInt16)throws  -> UInt16  {
    return try  FfiConverterUInt16.lift(try rustCallWithError(FfiConverterTypeIrisFfiError_lift) {
    uniffi_IrisCore_fn_method_ffibleadapter_set_mtu(
            self.uniffiCloneHandle(),
        FfiConverterUInt64.lower(handle),
        FfiConverterUInt16.lower(mtu),$0
    )
})
}
    
    /**
     * Drain inbound GATT writes (projection of the MutexGuard drain).
     */
open func incomingGattWrites() -> [FfiGattWriteEvent]  {
    return try!  FfiConverterSequenceTypeFfiGattWriteEvent.lift(try! rustCall() {
    uniffi_IrisCore_fn_method_ffibleadapter_incoming_gatt_writes(
            self.uniffiCloneHandle(),$0
    )
})
}
    
    /**
     * Drain scan results (projection of the MutexGuard drain).
     */
open func scanResults() -> [FfiScanResult]  {
    return try!  FfiConverterSequenceTypeFfiScanResult.lift(try! rustCall() {
    uniffi_IrisCore_fn_method_ffibleadapter_scan_results(
            self.uniffiCloneHandle(),$0
    )
})
}
    

    
}



// Put the implementation in a struct so we don't pollute the top-level namespace
fileprivate struct UniffiCallbackInterfaceFfiBleAdapter {

    // Create the VTable using a series of closures.
    // Swift automatically converts these into C callback functions.
    //
    // Store the vtable directly.
    static let vtable: UniffiVTableCallbackInterfaceFfiBleAdapter = UniffiVTableCallbackInterfaceFfiBleAdapter(
        uniffiFree: { (uniffiHandle: UInt64) -> () in
            do {
                try FfiConverterTypeFfiBleAdapter.handleMap.remove(handle: uniffiHandle)
            } catch {
                print("Uniffi callback interface FfiBleAdapter: handle missing in uniffiFree")
            }
        },
        uniffiClone: { (uniffiHandle: UInt64) -> UInt64 in
            do {
                return try FfiConverterTypeFfiBleAdapter.handleMap.clone(handle: uniffiHandle)
            } catch {
                fatalError("Uniffi callback interface FfiBleAdapter: handle missing in uniffiClone")
            }
        },
        startScan: { (
            uniffiHandle: UInt64,
            filter: RustBuffer,
            uniffiOutReturn: UnsafeMutablePointer<UInt64>,
            uniffiCallStatus: UnsafeMutablePointer<RustCallStatus>
        ) in
            let makeCall = {
                () throws -> UInt64 in
                guard let uniffiObj = try? FfiConverterTypeFfiBleAdapter.handleMap.get(handle: uniffiHandle) else {
                    throw UniffiInternalError.unexpectedStaleHandle
                }
                return try uniffiObj.startScan(
                     filter: try FfiConverterTypeFfiScanFilter_lift(filter)
                )
            }

            
            let writeReturn = { uniffiOutReturn.pointee = FfiConverterUInt64.lower($0) }
            uniffiTraitInterfaceCallWithError(
                callStatus: uniffiCallStatus,
                makeCall: makeCall,
                writeReturn: writeReturn,
                lowerError: FfiConverterTypeIrisFfiError_lower
            )
        },
        stopScan: { (
            uniffiHandle: UInt64,
            handle: UInt64,
            uniffiOutReturn: UnsafeMutableRawPointer,
            uniffiCallStatus: UnsafeMutablePointer<RustCallStatus>
        ) in
            let makeCall = {
                () throws -> () in
                guard let uniffiObj = try? FfiConverterTypeFfiBleAdapter.handleMap.get(handle: uniffiHandle) else {
                    throw UniffiInternalError.unexpectedStaleHandle
                }
                return uniffiObj.stopScan(
                     handle: try FfiConverterUInt64.lift(handle)
                )
            }

            
            let writeReturn = { () }
            uniffiTraitInterfaceCall(
                callStatus: uniffiCallStatus,
                makeCall: makeCall,
                writeReturn: writeReturn
            )
        },
        startAdvertising: { (
            uniffiHandle: UInt64,
            data: RustBuffer,
            uniffiOutReturn: UnsafeMutablePointer<UInt64>,
            uniffiCallStatus: UnsafeMutablePointer<RustCallStatus>
        ) in
            let makeCall = {
                () throws -> UInt64 in
                guard let uniffiObj = try? FfiConverterTypeFfiBleAdapter.handleMap.get(handle: uniffiHandle) else {
                    throw UniffiInternalError.unexpectedStaleHandle
                }
                return try uniffiObj.startAdvertising(
                     data: try FfiConverterTypeFfiAdvertisementData_lift(data)
                )
            }

            
            let writeReturn = { uniffiOutReturn.pointee = FfiConverterUInt64.lower($0) }
            uniffiTraitInterfaceCallWithError(
                callStatus: uniffiCallStatus,
                makeCall: makeCall,
                writeReturn: writeReturn,
                lowerError: FfiConverterTypeIrisFfiError_lower
            )
        },
        stopAdvertising: { (
            uniffiHandle: UInt64,
            handle: UInt64,
            uniffiOutReturn: UnsafeMutableRawPointer,
            uniffiCallStatus: UnsafeMutablePointer<RustCallStatus>
        ) in
            let makeCall = {
                () throws -> () in
                guard let uniffiObj = try? FfiConverterTypeFfiBleAdapter.handleMap.get(handle: uniffiHandle) else {
                    throw UniffiInternalError.unexpectedStaleHandle
                }
                return uniffiObj.stopAdvertising(
                     handle: try FfiConverterUInt64.lift(handle)
                )
            }

            
            let writeReturn = { () }
            uniffiTraitInterfaceCall(
                callStatus: uniffiCallStatus,
                makeCall: makeCall,
                writeReturn: writeReturn
            )
        },
        connectGatt: { (
            uniffiHandle: UInt64,
            address: RustBuffer,
            uniffiOutReturn: UnsafeMutablePointer<UInt64>,
            uniffiCallStatus: UnsafeMutablePointer<RustCallStatus>
        ) in
            let makeCall = {
                () throws -> UInt64 in
                guard let uniffiObj = try? FfiConverterTypeFfiBleAdapter.handleMap.get(handle: uniffiHandle) else {
                    throw UniffiInternalError.unexpectedStaleHandle
                }
                return try uniffiObj.connectGatt(
                     address: try FfiConverterString.lift(address)
                )
            }

            
            let writeReturn = { uniffiOutReturn.pointee = FfiConverterUInt64.lower($0) }
            uniffiTraitInterfaceCallWithError(
                callStatus: uniffiCallStatus,
                makeCall: makeCall,
                writeReturn: writeReturn,
                lowerError: FfiConverterTypeIrisFfiError_lower
            )
        },
        disconnectGatt: { (
            uniffiHandle: UInt64,
            handle: UInt64,
            uniffiOutReturn: UnsafeMutableRawPointer,
            uniffiCallStatus: UnsafeMutablePointer<RustCallStatus>
        ) in
            let makeCall = {
                () throws -> () in
                guard let uniffiObj = try? FfiConverterTypeFfiBleAdapter.handleMap.get(handle: uniffiHandle) else {
                    throw UniffiInternalError.unexpectedStaleHandle
                }
                return uniffiObj.disconnectGatt(
                     handle: try FfiConverterUInt64.lift(handle)
                )
            }

            
            let writeReturn = { () }
            uniffiTraitInterfaceCall(
                callStatus: uniffiCallStatus,
                makeCall: makeCall,
                writeReturn: writeReturn
            )
        },
        gattWrite: { (
            uniffiHandle: UInt64,
            handle: UInt64,
            charUuid: RustBuffer,
            data: RustBuffer,
            uniffiOutReturn: UnsafeMutableRawPointer,
            uniffiCallStatus: UnsafeMutablePointer<RustCallStatus>
        ) in
            let makeCall = {
                () throws -> () in
                guard let uniffiObj = try? FfiConverterTypeFfiBleAdapter.handleMap.get(handle: uniffiHandle) else {
                    throw UniffiInternalError.unexpectedStaleHandle
                }
                return try uniffiObj.gattWrite(
                     handle: try FfiConverterUInt64.lift(handle),
                     charUuid: try FfiConverterString.lift(charUuid),
                     data: try FfiConverterData.lift(data)
                )
            }

            
            let writeReturn = { () }
            uniffiTraitInterfaceCallWithError(
                callStatus: uniffiCallStatus,
                makeCall: makeCall,
                writeReturn: writeReturn,
                lowerError: FfiConverterTypeIrisFfiError_lower
            )
        },
        gattRead: { (
            uniffiHandle: UInt64,
            handle: UInt64,
            charUuid: RustBuffer,
            uniffiOutReturn: UnsafeMutablePointer<RustBuffer>,
            uniffiCallStatus: UnsafeMutablePointer<RustCallStatus>
        ) in
            let makeCall = {
                () throws -> Data in
                guard let uniffiObj = try? FfiConverterTypeFfiBleAdapter.handleMap.get(handle: uniffiHandle) else {
                    throw UniffiInternalError.unexpectedStaleHandle
                }
                return try uniffiObj.gattRead(
                     handle: try FfiConverterUInt64.lift(handle),
                     charUuid: try FfiConverterString.lift(charUuid)
                )
            }

            
            let writeReturn = { uniffiOutReturn.pointee = FfiConverterData.lower($0) }
            uniffiTraitInterfaceCallWithError(
                callStatus: uniffiCallStatus,
                makeCall: makeCall,
                writeReturn: writeReturn,
                lowerError: FfiConverterTypeIrisFfiError_lower
            )
        },
        setMtu: { (
            uniffiHandle: UInt64,
            handle: UInt64,
            mtu: UInt16,
            uniffiOutReturn: UnsafeMutablePointer<UInt16>,
            uniffiCallStatus: UnsafeMutablePointer<RustCallStatus>
        ) in
            let makeCall = {
                () throws -> UInt16 in
                guard let uniffiObj = try? FfiConverterTypeFfiBleAdapter.handleMap.get(handle: uniffiHandle) else {
                    throw UniffiInternalError.unexpectedStaleHandle
                }
                return try uniffiObj.setMtu(
                     handle: try FfiConverterUInt64.lift(handle),
                     mtu: try FfiConverterUInt16.lift(mtu)
                )
            }

            
            let writeReturn = { uniffiOutReturn.pointee = FfiConverterUInt16.lower($0) }
            uniffiTraitInterfaceCallWithError(
                callStatus: uniffiCallStatus,
                makeCall: makeCall,
                writeReturn: writeReturn,
                lowerError: FfiConverterTypeIrisFfiError_lower
            )
        },
        incomingGattWrites: { (
            uniffiHandle: UInt64,
            uniffiOutReturn: UnsafeMutablePointer<RustBuffer>,
            uniffiCallStatus: UnsafeMutablePointer<RustCallStatus>
        ) in
            let makeCall = {
                () throws -> [FfiGattWriteEvent] in
                guard let uniffiObj = try? FfiConverterTypeFfiBleAdapter.handleMap.get(handle: uniffiHandle) else {
                    throw UniffiInternalError.unexpectedStaleHandle
                }
                return uniffiObj.incomingGattWrites(
                )
            }

            
            let writeReturn = { uniffiOutReturn.pointee = FfiConverterSequenceTypeFfiGattWriteEvent.lower($0) }
            uniffiTraitInterfaceCall(
                callStatus: uniffiCallStatus,
                makeCall: makeCall,
                writeReturn: writeReturn
            )
        },
        scanResults: { (
            uniffiHandle: UInt64,
            uniffiOutReturn: UnsafeMutablePointer<RustBuffer>,
            uniffiCallStatus: UnsafeMutablePointer<RustCallStatus>
        ) in
            let makeCall = {
                () throws -> [FfiScanResult] in
                guard let uniffiObj = try? FfiConverterTypeFfiBleAdapter.handleMap.get(handle: uniffiHandle) else {
                    throw UniffiInternalError.unexpectedStaleHandle
                }
                return uniffiObj.scanResults(
                )
            }

            
            let writeReturn = { uniffiOutReturn.pointee = FfiConverterSequenceTypeFfiScanResult.lower($0) }
            uniffiTraitInterfaceCall(
                callStatus: uniffiCallStatus,
                makeCall: makeCall,
                writeReturn: writeReturn
            )
        }
    )

    // Rust stores this pointer for future callback invocations, so it must live
    // for the process lifetime (not just for the init function call).
    //
    // `nonisolated(unsafe)` is needed under Swift 6 strict concurrency.
    // This is safe because the pointee is initialized once during static init
    // and never mutated by either side of the FFI.  Its fields are C function pointers.
    nonisolated(unsafe) static let vtablePtr: UnsafePointer<UniffiVTableCallbackInterfaceFfiBleAdapter> = {
        let ptr = UnsafeMutablePointer<UniffiVTableCallbackInterfaceFfiBleAdapter>.allocate(capacity: 1)
        ptr.initialize(to: vtable)
        return UnsafePointer(ptr)
    }()
}

private func uniffiCallbackInitFfiBleAdapter() {
    uniffi_IrisCore_fn_init_callback_vtable_ffibleadapter(UniffiCallbackInterfaceFfiBleAdapter.vtablePtr)
}

#if swift(>=5.8)
@_documentation(visibility: private)
#endif
public struct FfiConverterTypeFfiBleAdapter: FfiConverter {
    fileprivate static let handleMap = UniffiHandleMap<FfiBleAdapter>()

    typealias FfiType = UInt64
    typealias SwiftType = FfiBleAdapter

    public static func lift(_ handle: UInt64) throws -> FfiBleAdapter {
        if ((handle & 1) == 0) {
            // Rust-generated handle, construct a new class that uses the handle to implement the
            // interface
            return FfiBleAdapterImpl(unsafeFromHandle: handle)
        } else {
            // Swift-generated handle, get the object from the handle map
            return try handleMap.remove(handle: handle)
        }
    }

    public static func lower(_ value: FfiBleAdapter) -> UInt64 {
         if let rustImpl = value as? FfiBleAdapterImpl {
             // Rust-implemented object.  Clone the handle and return it
            return rustImpl.uniffiCloneHandle()
         } else {
            // Swift object, generate a new vtable handle and return that.
            return handleMap.insert(obj: value)
         }
    }

    public static func read(from buf: inout (data: Data, offset: Data.Index)) throws -> FfiBleAdapter {
        let handle: UInt64 = try readInt(&buf)
        return try lift(handle)
    }

    public static func write(_ value: FfiBleAdapter, into buf: inout [UInt8]) {
        writeInt(&buf, lower(value))
    }
}


#if swift(>=5.8)
@_documentation(visibility: private)
#endif
public func FfiConverterTypeFfiBleAdapter_lift(_ handle: UInt64) throws -> FfiBleAdapter {
    return try FfiConverterTypeFfiBleAdapter.lift(handle)
}

#if swift(>=5.8)
@_documentation(visibility: private)
#endif
public func FfiConverterTypeFfiBleAdapter_lower(_ value: FfiBleAdapter) -> UInt64 {
    return FfiConverterTypeFfiBleAdapter.lower(value)
}






/**
 * Foreign-trait callback the Swift shell installs to receive delivered
 * messages. `#[async_trait]`-free: `on_message` is a synchronous notify.
 */
public protocol FfiInboxListener: AnyObject, Sendable {
    
    func onMessage(message: FfiIncomingMessage) 
    
}
/**
 * Foreign-trait callback the Swift shell installs to receive delivered
 * messages. `#[async_trait]`-free: `on_message` is a synchronous notify.
 */
open class FfiInboxListenerImpl: FfiInboxListener, @unchecked Sendable {
    fileprivate let handle: UInt64

    /// Used to instantiate a [FFIObject] without an actual handle, for fakes in tests, mostly.
#if swift(>=5.8)
    @_documentation(visibility: private)
#endif
    public struct NoHandle {
        public init() {}
    }

    // TODO: We'd like this to be `private` but for Swifty reasons,
    // we can't implement `FfiConverter` without making this `required` and we can't
    // make it `required` without making it `public`.
#if swift(>=5.8)
    @_documentation(visibility: private)
#endif
    required public init(unsafeFromHandle handle: UInt64) {
        self.handle = handle
    }

    // This constructor can be used to instantiate a fake object.
    // - Parameter noHandle: Placeholder value so we can have a constructor separate from the default empty one that may be implemented for classes extending [FFIObject].
    //
    // - Warning:
    //     Any object instantiated with this constructor cannot be passed to an actual Rust-backed object. Since there isn't a backing handle the FFI lower functions will crash.
#if swift(>=5.8)
    @_documentation(visibility: private)
#endif
    public init(noHandle: NoHandle) {
        self.handle = 0
    }

#if swift(>=5.8)
    @_documentation(visibility: private)
#endif
    public func uniffiCloneHandle() -> UInt64 {
        return try! rustCall { uniffi_IrisCore_fn_clone_ffiinboxlistener(self.handle, $0) }
    }
    // No primary constructor declared for this class.

    deinit {
        if handle == 0 {
            // Mock objects have handle=0 don't try to free them
            return
        }

        try! rustCall { uniffi_IrisCore_fn_free_ffiinboxlistener(handle, $0) }
    }

    

    
open func onMessage(message: FfiIncomingMessage)  {try! rustCall() {
    uniffi_IrisCore_fn_method_ffiinboxlistener_on_message(
            self.uniffiCloneHandle(),
        FfiConverterTypeFfiIncomingMessage_lower(message),$0
    )
}
}
    

    
}



// Put the implementation in a struct so we don't pollute the top-level namespace
fileprivate struct UniffiCallbackInterfaceFfiInboxListener {

    // Create the VTable using a series of closures.
    // Swift automatically converts these into C callback functions.
    //
    // Store the vtable directly.
    static let vtable: UniffiVTableCallbackInterfaceFfiInboxListener = UniffiVTableCallbackInterfaceFfiInboxListener(
        uniffiFree: { (uniffiHandle: UInt64) -> () in
            do {
                try FfiConverterTypeFfiInboxListener.handleMap.remove(handle: uniffiHandle)
            } catch {
                print("Uniffi callback interface FfiInboxListener: handle missing in uniffiFree")
            }
        },
        uniffiClone: { (uniffiHandle: UInt64) -> UInt64 in
            do {
                return try FfiConverterTypeFfiInboxListener.handleMap.clone(handle: uniffiHandle)
            } catch {
                fatalError("Uniffi callback interface FfiInboxListener: handle missing in uniffiClone")
            }
        },
        onMessage: { (
            uniffiHandle: UInt64,
            message: RustBuffer,
            uniffiOutReturn: UnsafeMutableRawPointer,
            uniffiCallStatus: UnsafeMutablePointer<RustCallStatus>
        ) in
            let makeCall = {
                () throws -> () in
                guard let uniffiObj = try? FfiConverterTypeFfiInboxListener.handleMap.get(handle: uniffiHandle) else {
                    throw UniffiInternalError.unexpectedStaleHandle
                }
                return uniffiObj.onMessage(
                     message: try FfiConverterTypeFfiIncomingMessage_lift(message)
                )
            }

            
            let writeReturn = { () }
            uniffiTraitInterfaceCall(
                callStatus: uniffiCallStatus,
                makeCall: makeCall,
                writeReturn: writeReturn
            )
        }
    )

    // Rust stores this pointer for future callback invocations, so it must live
    // for the process lifetime (not just for the init function call).
    //
    // `nonisolated(unsafe)` is needed under Swift 6 strict concurrency.
    // This is safe because the pointee is initialized once during static init
    // and never mutated by either side of the FFI.  Its fields are C function pointers.
    nonisolated(unsafe) static let vtablePtr: UnsafePointer<UniffiVTableCallbackInterfaceFfiInboxListener> = {
        let ptr = UnsafeMutablePointer<UniffiVTableCallbackInterfaceFfiInboxListener>.allocate(capacity: 1)
        ptr.initialize(to: vtable)
        return UnsafePointer(ptr)
    }()
}

private func uniffiCallbackInitFfiInboxListener() {
    uniffi_IrisCore_fn_init_callback_vtable_ffiinboxlistener(UniffiCallbackInterfaceFfiInboxListener.vtablePtr)
}

#if swift(>=5.8)
@_documentation(visibility: private)
#endif
public struct FfiConverterTypeFfiInboxListener: FfiConverter {
    fileprivate static let handleMap = UniffiHandleMap<FfiInboxListener>()

    typealias FfiType = UInt64
    typealias SwiftType = FfiInboxListener

    public static func lift(_ handle: UInt64) throws -> FfiInboxListener {
        if ((handle & 1) == 0) {
            // Rust-generated handle, construct a new class that uses the handle to implement the
            // interface
            return FfiInboxListenerImpl(unsafeFromHandle: handle)
        } else {
            // Swift-generated handle, get the object from the handle map
            return try handleMap.remove(handle: handle)
        }
    }

    public static func lower(_ value: FfiInboxListener) -> UInt64 {
         if let rustImpl = value as? FfiInboxListenerImpl {
             // Rust-implemented object.  Clone the handle and return it
            return rustImpl.uniffiCloneHandle()
         } else {
            // Swift object, generate a new vtable handle and return that.
            return handleMap.insert(obj: value)
         }
    }

    public static func read(from buf: inout (data: Data, offset: Data.Index)) throws -> FfiInboxListener {
        let handle: UInt64 = try readInt(&buf)
        return try lift(handle)
    }

    public static func write(_ value: FfiInboxListener, into buf: inout [UInt8]) {
        writeInt(&buf, lower(value))
    }
}


#if swift(>=5.8)
@_documentation(visibility: private)
#endif
public func FfiConverterTypeFfiInboxListener_lift(_ handle: UInt64) throws -> FfiInboxListener {
    return try FfiConverterTypeFfiInboxListener.lift(handle)
}

#if swift(>=5.8)
@_documentation(visibility: private)
#endif
public func FfiConverterTypeFfiInboxListener_lower(_ value: FfiInboxListener) -> UInt64 {
    return FfiConverterTypeFfiInboxListener.lower(value)
}






/**
 * Foreign body renderer implemented by the Swift shell (protocol `IrisBody`).
 * `@unchecked Sendable` on the Swift implementation class (the generated
 * protocol is `Sendable`; mutable CoreBluetooth/Keychain state is confined to
 * a dedicated serial queue — IOS_DESIGN D-1 / §8).
 */
public protocol IrisBody: AnyObject, Sendable {
    
    /**
     * Synchronous presentation hook (notifications; Live Activity status).
     */
    func summarize(envelope: FfiIrisEnvelope)  -> String
    
    /**
     * Async body surface (foreign-future bridge proof; Swift `async` method).
     * Must return success for a well-formed envelope.
     */
    func describe(envelope: FfiIrisEnvelope) async throws  -> String
    
}
/**
 * Foreign body renderer implemented by the Swift shell (protocol `IrisBody`).
 * `@unchecked Sendable` on the Swift implementation class (the generated
 * protocol is `Sendable`; mutable CoreBluetooth/Keychain state is confined to
 * a dedicated serial queue — IOS_DESIGN D-1 / §8).
 */
open class IrisBodyImpl: IrisBody, @unchecked Sendable {
    fileprivate let handle: UInt64

    /// Used to instantiate a [FFIObject] without an actual handle, for fakes in tests, mostly.
#if swift(>=5.8)
    @_documentation(visibility: private)
#endif
    public struct NoHandle {
        public init() {}
    }

    // TODO: We'd like this to be `private` but for Swifty reasons,
    // we can't implement `FfiConverter` without making this `required` and we can't
    // make it `required` without making it `public`.
#if swift(>=5.8)
    @_documentation(visibility: private)
#endif
    required public init(unsafeFromHandle handle: UInt64) {
        self.handle = handle
    }

    // This constructor can be used to instantiate a fake object.
    // - Parameter noHandle: Placeholder value so we can have a constructor separate from the default empty one that may be implemented for classes extending [FFIObject].
    //
    // - Warning:
    //     Any object instantiated with this constructor cannot be passed to an actual Rust-backed object. Since there isn't a backing handle the FFI lower functions will crash.
#if swift(>=5.8)
    @_documentation(visibility: private)
#endif
    public init(noHandle: NoHandle) {
        self.handle = 0
    }

#if swift(>=5.8)
    @_documentation(visibility: private)
#endif
    public func uniffiCloneHandle() -> UInt64 {
        return try! rustCall { uniffi_IrisCore_fn_clone_irisbody(self.handle, $0) }
    }
    // No primary constructor declared for this class.

    deinit {
        if handle == 0 {
            // Mock objects have handle=0 don't try to free them
            return
        }

        try! rustCall { uniffi_IrisCore_fn_free_irisbody(handle, $0) }
    }

    

    
    /**
     * Synchronous presentation hook (notifications; Live Activity status).
     */
open func summarize(envelope: FfiIrisEnvelope) -> String  {
    return try!  FfiConverterString.lift(try! rustCall() {
    uniffi_IrisCore_fn_method_irisbody_summarize(
            self.uniffiCloneHandle(),
        FfiConverterTypeFfiIrisEnvelope_lower(envelope),$0
    )
})
}
    
    /**
     * Async body surface (foreign-future bridge proof; Swift `async` method).
     * Must return success for a well-formed envelope.
     */
open func describe(envelope: FfiIrisEnvelope)async throws  -> String  {
    return
        try  await uniffiRustCallAsync(
            rustFutureFunc: {
                uniffi_IrisCore_fn_method_irisbody_describe(
                    self.uniffiCloneHandle(),
                    FfiConverterTypeFfiIrisEnvelope_lower(envelope)
                )
            },
            pollFunc: ffi_IrisCore_rust_future_poll_rust_buffer,
            completeFunc: ffi_IrisCore_rust_future_complete_rust_buffer,
            freeFunc: ffi_IrisCore_rust_future_free_rust_buffer,
            liftFunc: FfiConverterString.lift,
            errorHandler: FfiConverterTypeIrisFfiError_lift
        )
}
    

    
}



// Put the implementation in a struct so we don't pollute the top-level namespace
fileprivate struct UniffiCallbackInterfaceIrisBody {

    // Create the VTable using a series of closures.
    // Swift automatically converts these into C callback functions.
    //
    // Store the vtable directly.
    static let vtable: UniffiVTableCallbackInterfaceIrisBody = UniffiVTableCallbackInterfaceIrisBody(
        uniffiFree: { (uniffiHandle: UInt64) -> () in
            do {
                try FfiConverterTypeIrisBody.handleMap.remove(handle: uniffiHandle)
            } catch {
                print("Uniffi callback interface IrisBody: handle missing in uniffiFree")
            }
        },
        uniffiClone: { (uniffiHandle: UInt64) -> UInt64 in
            do {
                return try FfiConverterTypeIrisBody.handleMap.clone(handle: uniffiHandle)
            } catch {
                fatalError("Uniffi callback interface IrisBody: handle missing in uniffiClone")
            }
        },
        summarize: { (
            uniffiHandle: UInt64,
            envelope: RustBuffer,
            uniffiOutReturn: UnsafeMutablePointer<RustBuffer>,
            uniffiCallStatus: UnsafeMutablePointer<RustCallStatus>
        ) in
            let makeCall = {
                () throws -> String in
                guard let uniffiObj = try? FfiConverterTypeIrisBody.handleMap.get(handle: uniffiHandle) else {
                    throw UniffiInternalError.unexpectedStaleHandle
                }
                return uniffiObj.summarize(
                     envelope: try FfiConverterTypeFfiIrisEnvelope_lift(envelope)
                )
            }

            
            let writeReturn = { uniffiOutReturn.pointee = FfiConverterString.lower($0) }
            uniffiTraitInterfaceCall(
                callStatus: uniffiCallStatus,
                makeCall: makeCall,
                writeReturn: writeReturn
            )
        },
        describe: { (
            uniffiHandle: UInt64,
            envelope: RustBuffer,
            uniffiFutureCallback: @escaping UniffiForeignFutureCompleteRustBuffer,
            uniffiCallbackData: UInt64,
            uniffiOutDroppedCallback: UnsafeMutablePointer<UniffiForeignFutureDroppedCallbackStruct>
        ) in
            let makeCall = {
                () async throws -> String in
                guard let uniffiObj = try? FfiConverterTypeIrisBody.handleMap.get(handle: uniffiHandle) else {
                    throw UniffiInternalError.unexpectedStaleHandle
                }
                return try await uniffiObj.describe(
                     envelope: try FfiConverterTypeFfiIrisEnvelope_lift(envelope)
                )
            }

            let uniffiHandleSuccess = { (returnValue: String) in
                uniffiFutureCallback(
                    uniffiCallbackData,
                    UniffiForeignFutureResultRustBuffer(
                        returnValue: FfiConverterString.lower(returnValue),
                        callStatus: RustCallStatus()
                    )
                )
            }
            let uniffiHandleError = { (statusCode, errorBuf) in
                uniffiFutureCallback(
                    uniffiCallbackData,
                    UniffiForeignFutureResultRustBuffer(
                        returnValue: RustBuffer.empty(),
                        callStatus: RustCallStatus(code: statusCode, errorBuf: errorBuf)
                    )
                )
            }
            uniffiTraitInterfaceCallAsyncWithError(
                makeCall: makeCall,
                handleSuccess: uniffiHandleSuccess,
                handleError: uniffiHandleError,
                lowerError: FfiConverterTypeIrisFfiError_lower,
                droppedCallback: uniffiOutDroppedCallback
            )
        }
    )

    // Rust stores this pointer for future callback invocations, so it must live
    // for the process lifetime (not just for the init function call).
    //
    // `nonisolated(unsafe)` is needed under Swift 6 strict concurrency.
    // This is safe because the pointee is initialized once during static init
    // and never mutated by either side of the FFI.  Its fields are C function pointers.
    nonisolated(unsafe) static let vtablePtr: UnsafePointer<UniffiVTableCallbackInterfaceIrisBody> = {
        let ptr = UnsafeMutablePointer<UniffiVTableCallbackInterfaceIrisBody>.allocate(capacity: 1)
        ptr.initialize(to: vtable)
        return UnsafePointer(ptr)
    }()
}

private func uniffiCallbackInitIrisBody() {
    uniffi_IrisCore_fn_init_callback_vtable_irisbody(UniffiCallbackInterfaceIrisBody.vtablePtr)
}

#if swift(>=5.8)
@_documentation(visibility: private)
#endif
public struct FfiConverterTypeIrisBody: FfiConverter {
    fileprivate static let handleMap = UniffiHandleMap<IrisBody>()

    typealias FfiType = UInt64
    typealias SwiftType = IrisBody

    public static func lift(_ handle: UInt64) throws -> IrisBody {
        if ((handle & 1) == 0) {
            // Rust-generated handle, construct a new class that uses the handle to implement the
            // interface
            return IrisBodyImpl(unsafeFromHandle: handle)
        } else {
            // Swift-generated handle, get the object from the handle map
            return try handleMap.remove(handle: handle)
        }
    }

    public static func lower(_ value: IrisBody) -> UInt64 {
         if let rustImpl = value as? IrisBodyImpl {
             // Rust-implemented object.  Clone the handle and return it
            return rustImpl.uniffiCloneHandle()
         } else {
            // Swift object, generate a new vtable handle and return that.
            return handleMap.insert(obj: value)
         }
    }

    public static func read(from buf: inout (data: Data, offset: Data.Index)) throws -> IrisBody {
        let handle: UInt64 = try readInt(&buf)
        return try lift(handle)
    }

    public static func write(_ value: IrisBody, into buf: inout [UInt8]) {
        writeInt(&buf, lower(value))
    }
}


#if swift(>=5.8)
@_documentation(visibility: private)
#endif
public func FfiConverterTypeIrisBody_lift(_ handle: UInt64) throws -> IrisBody {
    return try FfiConverterTypeIrisBody.lift(handle)
}

#if swift(>=5.8)
@_documentation(visibility: private)
#endif
public func FfiConverterTypeIrisBody_lower(_ value: IrisBody) -> UInt64 {
    return FfiConverterTypeIrisBody.lower(value)
}






/**
 * The iOS app's engine host. Owns the injected `BleAdapter` foreign trait,
 * the transport manager, the message engine, and the `IrisBody` renderer — all
 * driven by a tokio runtime whose handle is threaded through every poll path.
 */
public protocol IrisEngineProtocol: AnyObject, Sendable {
    
    /**
     * The node's 32-byte PeerId for outbound messages.
     */
    func nodeId()  -> Data
    
    /**
     * Send a text message to `recipient_hex` (64-hex node id). Returns the
     * 16-byte wire message id on acceptance.
     */
    func sendText(recipientHex: String, text: String, priority: UInt8) throws  -> Data
    
    /**
     * Install the Swift `IrisBody` renderer (envelope-body surface, ffi::body).
     */
    func setBodyRenderer(renderer: IrisBody) 
    
    /**
     * Bring the BLE mesh transport up: `start_advertising` triggers its
     * adapter bring-up (scan + advertise) and spawns the inbound poller.
     */
    func startAll() throws 
    
    /**
     * Shut down the message engine and the BLE transport (async teardown
     * through the handle).
     */
    func stopAll() throws 
    
    /**
     * Stream delivered messages to a Swift `FfiInboxListener`. The listener
     * is invoked from a task on the engine's runtime; if an `IrisBody`
     * renderer is installed the envelope projection is handed to it first.
     */
    func subscribeInbox(listener: FfiInboxListener) throws 
    
}
/**
 * The iOS app's engine host. Owns the injected `BleAdapter` foreign trait,
 * the transport manager, the message engine, and the `IrisBody` renderer — all
 * driven by a tokio runtime whose handle is threaded through every poll path.
 */
open class IrisEngine: IrisEngineProtocol, @unchecked Sendable {
    fileprivate let handle: UInt64

    /// Used to instantiate a [FFIObject] without an actual handle, for fakes in tests, mostly.
#if swift(>=5.8)
    @_documentation(visibility: private)
#endif
    public struct NoHandle {
        public init() {}
    }

    // TODO: We'd like this to be `private` but for Swifty reasons,
    // we can't implement `FfiConverter` without making this `required` and we can't
    // make it `required` without making it `public`.
#if swift(>=5.8)
    @_documentation(visibility: private)
#endif
    required public init(unsafeFromHandle handle: UInt64) {
        self.handle = handle
    }

    // This constructor can be used to instantiate a fake object.
    // - Parameter noHandle: Placeholder value so we can have a constructor separate from the default empty one that may be implemented for classes extending [FFIObject].
    //
    // - Warning:
    //     Any object instantiated with this constructor cannot be passed to an actual Rust-backed object. Since there isn't a backing handle the FFI lower functions will crash.
#if swift(>=5.8)
    @_documentation(visibility: private)
#endif
    public init(noHandle: NoHandle) {
        self.handle = 0
    }

#if swift(>=5.8)
    @_documentation(visibility: private)
#endif
    public func uniffiCloneHandle() -> UInt64 {
        return try! rustCall { uniffi_IrisCore_fn_clone_irisengine(self.handle, $0) }
    }
    /**
     * Build the engine host with the injected Swift `IosBleAdapter`
     * (DEC-IOS-0003: the tokio runtime is constructed here and its handle
     * drives every poller). The BLE transport is registered over the FFI
     * bridge; the MessageEngine and the inbox forwarder are wired before the
     * engine returns.
     */
public convenience init(ble: FfiBleAdapter, nodeId: Data)throws  {
    let handle =
        try rustCallWithError(FfiConverterTypeIrisFfiError_lift) {
    uniffi_IrisCore_fn_constructor_irisengine_new(
        FfiConverterTypeFfiBleAdapter_lower(ble),
        FfiConverterData.lower(nodeId),$0
    )
}
    self.init(unsafeFromHandle: handle)
}

    deinit {
        if handle == 0 {
            // Mock objects have handle=0 don't try to free them
            return
        }

        try! rustCall { uniffi_IrisCore_fn_free_irisengine(handle, $0) }
    }

    

    
    /**
     * The node's 32-byte PeerId for outbound messages.
     */
open func nodeId() -> Data  {
    return try!  FfiConverterData.lift(try! rustCall() {
    uniffi_IrisCore_fn_method_irisengine_node_id(
            self.uniffiCloneHandle(),$0
    )
})
}
    
    /**
     * Send a text message to `recipient_hex` (64-hex node id). Returns the
     * 16-byte wire message id on acceptance.
     */
open func sendText(recipientHex: String, text: String, priority: UInt8)throws  -> Data  {
    return try  FfiConverterData.lift(try rustCallWithError(FfiConverterTypeIrisFfiError_lift) {
    uniffi_IrisCore_fn_method_irisengine_send_text(
            self.uniffiCloneHandle(),
        FfiConverterString.lower(recipientHex),
        FfiConverterString.lower(text),
        FfiConverterUInt8.lower(priority),$0
    )
})
}
    
    /**
     * Install the Swift `IrisBody` renderer (envelope-body surface, ffi::body).
     */
open func setBodyRenderer(renderer: IrisBody)  {try! rustCall() {
    uniffi_IrisCore_fn_method_irisengine_set_body_renderer(
            self.uniffiCloneHandle(),
        FfiConverterTypeIrisBody_lower(renderer),$0
    )
}
}
    
    /**
     * Bring the BLE mesh transport up: `start_advertising` triggers its
     * adapter bring-up (scan + advertise) and spawns the inbound poller.
     */
open func startAll()throws   {try rustCallWithError(FfiConverterTypeIrisFfiError_lift) {
    uniffi_IrisCore_fn_method_irisengine_start_all(
            self.uniffiCloneHandle(),$0
    )
}
}
    
    /**
     * Shut down the message engine and the BLE transport (async teardown
     * through the handle).
     */
open func stopAll()throws   {try rustCallWithError(FfiConverterTypeIrisFfiError_lift) {
    uniffi_IrisCore_fn_method_irisengine_stop_all(
            self.uniffiCloneHandle(),$0
    )
}
}
    
    /**
     * Stream delivered messages to a Swift `FfiInboxListener`. The listener
     * is invoked from a task on the engine's runtime; if an `IrisBody`
     * renderer is installed the envelope projection is handed to it first.
     */
open func subscribeInbox(listener: FfiInboxListener)throws   {try rustCallWithError(FfiConverterTypeIrisFfiError_lift) {
    uniffi_IrisCore_fn_method_irisengine_subscribe_inbox(
            self.uniffiCloneHandle(),
        FfiConverterTypeFfiInboxListener_lower(listener),$0
    )
}
}
    

    
}


#if swift(>=5.8)
@_documentation(visibility: private)
#endif
public struct FfiConverterTypeIrisEngine: FfiConverter {
    typealias FfiType = UInt64
    typealias SwiftType = IrisEngine

    public static func lift(_ handle: UInt64) throws -> IrisEngine {
        return IrisEngine(unsafeFromHandle: handle)
    }

    public static func lower(_ value: IrisEngine) -> UInt64 {
        return value.uniffiCloneHandle()
    }

    public static func read(from buf: inout (data: Data, offset: Data.Index)) throws -> IrisEngine {
        let handle: UInt64 = try readInt(&buf)
        return try lift(handle)
    }

    public static func write(_ value: IrisEngine, into buf: inout [UInt8]) {
        writeInt(&buf, lower(value))
    }
}


#if swift(>=5.8)
@_documentation(visibility: private)
#endif
public func FfiConverterTypeIrisEngine_lift(_ handle: UInt64) throws -> IrisEngine {
    return try FfiConverterTypeIrisEngine.lift(handle)
}

#if swift(>=5.8)
@_documentation(visibility: private)
#endif
public func FfiConverterTypeIrisEngine_lower(_ value: IrisEngine) -> UInt64 {
    return FfiConverterTypeIrisEngine.lower(value)
}




/**
 * Owned advertisement payload for the discovery beacon (`ble::AdvertisementData`).
 */
public struct FfiAdvertisementData: Equatable, Hashable {
    /**
     * Raw bytes the platform must advertise. On iOS the beacon is NEVER on
     * the wire as ad data (CoreBluetooth has no service/manufacturer data);
     * `IosBleAdapter` serves it from `IRIS_IDENTIFY_CHARACTERISTIC` instead
     * (connect-to-identify, DEC-BLE-002-0002).
     */
    public var payload: Data
    /**
     * When true, advertise as non-connectable (broadcast beacon).
     */
    public var nonConnectable: Bool

    // Default memberwise initializers are never public by default, so we
    // declare one manually.
    public init(
        /**
         * Raw bytes the platform must advertise. On iOS the beacon is NEVER on
         * the wire as ad data (CoreBluetooth has no service/manufacturer data);
         * `IosBleAdapter` serves it from `IRIS_IDENTIFY_CHARACTERISTIC` instead
         * (connect-to-identify, DEC-BLE-002-0002).
         */payload: Data, 
        /**
         * When true, advertise as non-connectable (broadcast beacon).
         */nonConnectable: Bool) {
        self.payload = payload
        self.nonConnectable = nonConnectable
    }

    

    
}

#if compiler(>=6)
extension FfiAdvertisementData: Sendable {}
#endif

#if swift(>=5.8)
@_documentation(visibility: private)
#endif
public struct FfiConverterTypeFfiAdvertisementData: FfiConverterRustBuffer {
    public static func read(from buf: inout (data: Data, offset: Data.Index)) throws -> FfiAdvertisementData {
        return
            try FfiAdvertisementData(
                payload: FfiConverterData.read(from: &buf), 
                nonConnectable: FfiConverterBool.read(from: &buf)
        )
    }

    public static func write(_ value: FfiAdvertisementData, into buf: inout [UInt8]) {
        FfiConverterData.write(value.payload, into: &buf)
        FfiConverterBool.write(value.nonConnectable, into: &buf)
    }
}


#if swift(>=5.8)
@_documentation(visibility: private)
#endif
public func FfiConverterTypeFfiAdvertisementData_lift(_ buf: RustBuffer) throws -> FfiAdvertisementData {
    return try FfiConverterTypeFfiAdvertisementData.lift(buf)
}

#if swift(>=5.8)
@_documentation(visibility: private)
#endif
public func FfiConverterTypeFfiAdvertisementData_lower(_ value: FfiAdvertisementData) -> RustBuffer {
    return FfiConverterTypeFfiAdvertisementData.lower(value)
}


/**
 * Owned inbound GATT write (`ble::GattWriteEvent`; replaces the MutexGuard drain).
 */
public struct FfiGattWriteEvent: Equatable, Hashable {
    /**
     * Peer attribute handle.
     */
    public var handle: UInt64
    /**
     * Characteristic UUID hex.
     */
    public var charUuid: String
    public var data: Data

    // Default memberwise initializers are never public by default, so we
    // declare one manually.
    public init(
        /**
         * Peer attribute handle.
         */handle: UInt64, 
        /**
         * Characteristic UUID hex.
         */charUuid: String, data: Data) {
        self.handle = handle
        self.charUuid = charUuid
        self.data = data
    }

    

    
}

#if compiler(>=6)
extension FfiGattWriteEvent: Sendable {}
#endif

#if swift(>=5.8)
@_documentation(visibility: private)
#endif
public struct FfiConverterTypeFfiGattWriteEvent: FfiConverterRustBuffer {
    public static func read(from buf: inout (data: Data, offset: Data.Index)) throws -> FfiGattWriteEvent {
        return
            try FfiGattWriteEvent(
                handle: FfiConverterUInt64.read(from: &buf), 
                charUuid: FfiConverterString.read(from: &buf), 
                data: FfiConverterData.read(from: &buf)
        )
    }

    public static func write(_ value: FfiGattWriteEvent, into buf: inout [UInt8]) {
        FfiConverterUInt64.write(value.handle, into: &buf)
        FfiConverterString.write(value.charUuid, into: &buf)
        FfiConverterData.write(value.data, into: &buf)
    }
}


#if swift(>=5.8)
@_documentation(visibility: private)
#endif
public func FfiConverterTypeFfiGattWriteEvent_lift(_ buf: RustBuffer) throws -> FfiGattWriteEvent {
    return try FfiConverterTypeFfiGattWriteEvent.lift(buf)
}

#if swift(>=5.8)
@_documentation(visibility: private)
#endif
public func FfiConverterTypeFfiGattWriteEvent_lower(_ value: FfiGattWriteEvent) -> RustBuffer {
    return FfiConverterTypeFfiGattWriteEvent.lower(value)
}


/**
 * A delivered message handed to the Swift shell (`subscribe_inbox`).
 */
public struct FfiIncomingMessage: Equatable, Hashable {
    public var senderId: Data
    public var messageId: Data
    public var recipientId: Data
    public var payload: Data
    /**
     * 0 = P0 … 7 = P7.
     */
    public var priority: UInt8
    /**
     * Unix epoch milliseconds at origination.
     */
    public var receivedAtMs: UInt64

    // Default memberwise initializers are never public by default, so we
    // declare one manually.
    public init(senderId: Data, messageId: Data, recipientId: Data, payload: Data, 
        /**
         * 0 = P0 … 7 = P7.
         */priority: UInt8, 
        /**
         * Unix epoch milliseconds at origination.
         */receivedAtMs: UInt64) {
        self.senderId = senderId
        self.messageId = messageId
        self.recipientId = recipientId
        self.payload = payload
        self.priority = priority
        self.receivedAtMs = receivedAtMs
    }

    

    
}

#if compiler(>=6)
extension FfiIncomingMessage: Sendable {}
#endif

#if swift(>=5.8)
@_documentation(visibility: private)
#endif
public struct FfiConverterTypeFfiIncomingMessage: FfiConverterRustBuffer {
    public static func read(from buf: inout (data: Data, offset: Data.Index)) throws -> FfiIncomingMessage {
        return
            try FfiIncomingMessage(
                senderId: FfiConverterData.read(from: &buf), 
                messageId: FfiConverterData.read(from: &buf), 
                recipientId: FfiConverterData.read(from: &buf), 
                payload: FfiConverterData.read(from: &buf), 
                priority: FfiConverterUInt8.read(from: &buf), 
                receivedAtMs: FfiConverterUInt64.read(from: &buf)
        )
    }

    public static func write(_ value: FfiIncomingMessage, into buf: inout [UInt8]) {
        FfiConverterData.write(value.senderId, into: &buf)
        FfiConverterData.write(value.messageId, into: &buf)
        FfiConverterData.write(value.recipientId, into: &buf)
        FfiConverterData.write(value.payload, into: &buf)
        FfiConverterUInt8.write(value.priority, into: &buf)
        FfiConverterUInt64.write(value.receivedAtMs, into: &buf)
    }
}


#if swift(>=5.8)
@_documentation(visibility: private)
#endif
public func FfiConverterTypeFfiIncomingMessage_lift(_ buf: RustBuffer) throws -> FfiIncomingMessage {
    return try FfiConverterTypeFfiIncomingMessage.lift(buf)
}

#if swift(>=5.8)
@_documentation(visibility: private)
#endif
public func FfiConverterTypeFfiIncomingMessage_lower(_ value: FfiIncomingMessage) -> RustBuffer {
    return FfiConverterTypeFfiIncomingMessage.lower(value)
}


/**
 * Owned envelope projection handed to the Swift body renderer.
 */
public struct FfiIrisEnvelope: Equatable, Hashable {
    /**
     * 16-byte wire message id.
     */
    public var messageId: Data
    /**
     * 32-byte sender node id.
     */
    public var senderId: Data
    /**
     * 32-byte recipient node id.
     */
    public var recipientId: Data
    /**
     * 0 = P0 … 7 = P7.
     */
    public var priority: UInt8
    /**
     * Unix epoch milliseconds at origination.
     */
    public var originatedAtMs: UInt64
    /**
     * Encrypted body bytes (the shell never stores/exposes this beyond
     * presentation seams).
     */
    public var payload: Data

    // Default memberwise initializers are never public by default, so we
    // declare one manually.
    public init(
        /**
         * 16-byte wire message id.
         */messageId: Data, 
        /**
         * 32-byte sender node id.
         */senderId: Data, 
        /**
         * 32-byte recipient node id.
         */recipientId: Data, 
        /**
         * 0 = P0 … 7 = P7.
         */priority: UInt8, 
        /**
         * Unix epoch milliseconds at origination.
         */originatedAtMs: UInt64, 
        /**
         * Encrypted body bytes (the shell never stores/exposes this beyond
         * presentation seams).
         */payload: Data) {
        self.messageId = messageId
        self.senderId = senderId
        self.recipientId = recipientId
        self.priority = priority
        self.originatedAtMs = originatedAtMs
        self.payload = payload
    }

    

    
}

#if compiler(>=6)
extension FfiIrisEnvelope: Sendable {}
#endif

#if swift(>=5.8)
@_documentation(visibility: private)
#endif
public struct FfiConverterTypeFfiIrisEnvelope: FfiConverterRustBuffer {
    public static func read(from buf: inout (data: Data, offset: Data.Index)) throws -> FfiIrisEnvelope {
        return
            try FfiIrisEnvelope(
                messageId: FfiConverterData.read(from: &buf), 
                senderId: FfiConverterData.read(from: &buf), 
                recipientId: FfiConverterData.read(from: &buf), 
                priority: FfiConverterUInt8.read(from: &buf), 
                originatedAtMs: FfiConverterUInt64.read(from: &buf), 
                payload: FfiConverterData.read(from: &buf)
        )
    }

    public static func write(_ value: FfiIrisEnvelope, into buf: inout [UInt8]) {
        FfiConverterData.write(value.messageId, into: &buf)
        FfiConverterData.write(value.senderId, into: &buf)
        FfiConverterData.write(value.recipientId, into: &buf)
        FfiConverterUInt8.write(value.priority, into: &buf)
        FfiConverterUInt64.write(value.originatedAtMs, into: &buf)
        FfiConverterData.write(value.payload, into: &buf)
    }
}


#if swift(>=5.8)
@_documentation(visibility: private)
#endif
public func FfiConverterTypeFfiIrisEnvelope_lift(_ buf: RustBuffer) throws -> FfiIrisEnvelope {
    return try FfiConverterTypeFfiIrisEnvelope.lift(buf)
}

#if swift(>=5.8)
@_documentation(visibility: private)
#endif
public func FfiConverterTypeFfiIrisEnvelope_lower(_ value: FfiIrisEnvelope) -> RustBuffer {
    return FfiConverterTypeFfiIrisEnvelope.lower(value)
}


/**
 * Owned scan filter (mirrors `ble::ScanFilter` fields flattened to FFI-safe).
 */
public struct FfiScanFilter: Equatable, Hashable {
    /**
     * Service UUID hex ("" = all). The Swift `IosBleAdapter` REQUIRES this to
     * be the IRIS service UUID for background scanning (AC-9); UUID-less
     * configs are rejected.
     */
    public var serviceUuid: String
    /**
     * Address to filter on ("" = any).
     */
    public var address: String
    /**
     * RSSI floor dBm (e.g. -95).
     */
    public var rssiFloor: Int32

    // Default memberwise initializers are never public by default, so we
    // declare one manually.
    public init(
        /**
         * Service UUID hex ("" = all). The Swift `IosBleAdapter` REQUIRES this to
         * be the IRIS service UUID for background scanning (AC-9); UUID-less
         * configs are rejected.
         */serviceUuid: String, 
        /**
         * Address to filter on ("" = any).
         */address: String, 
        /**
         * RSSI floor dBm (e.g. -95).
         */rssiFloor: Int32) {
        self.serviceUuid = serviceUuid
        self.address = address
        self.rssiFloor = rssiFloor
    }

    

    
}

#if compiler(>=6)
extension FfiScanFilter: Sendable {}
#endif

#if swift(>=5.8)
@_documentation(visibility: private)
#endif
public struct FfiConverterTypeFfiScanFilter: FfiConverterRustBuffer {
    public static func read(from buf: inout (data: Data, offset: Data.Index)) throws -> FfiScanFilter {
        return
            try FfiScanFilter(
                serviceUuid: FfiConverterString.read(from: &buf), 
                address: FfiConverterString.read(from: &buf), 
                rssiFloor: FfiConverterInt32.read(from: &buf)
        )
    }

    public static func write(_ value: FfiScanFilter, into buf: inout [UInt8]) {
        FfiConverterString.write(value.serviceUuid, into: &buf)
        FfiConverterString.write(value.address, into: &buf)
        FfiConverterInt32.write(value.rssiFloor, into: &buf)
    }
}


#if swift(>=5.8)
@_documentation(visibility: private)
#endif
public func FfiConverterTypeFfiScanFilter_lift(_ buf: RustBuffer) throws -> FfiScanFilter {
    return try FfiConverterTypeFfiScanFilter.lift(buf)
}

#if swift(>=5.8)
@_documentation(visibility: private)
#endif
public func FfiConverterTypeFfiScanFilter_lower(_ value: FfiScanFilter) -> RustBuffer {
    return FfiConverterTypeFfiScanFilter.lower(value)
}


/**
 * Owned scan-result drain (`ble::ScanResult`; replaces the MutexGuard drain).
 */
public struct FfiScanResult: Equatable, Hashable {
    public var address: String
    /**
     * Empty on iOS: advertisementData carries NO IRIS service data (RES-0024
     * DI-1) — RSSI + identity only; the connect-to-identify branch probes
     * empty-payload results.
     */
    public var payload: Data
    public var rssi: Int32

    // Default memberwise initializers are never public by default, so we
    // declare one manually.
    public init(address: String, 
        /**
         * Empty on iOS: advertisementData carries NO IRIS service data (RES-0024
         * DI-1) — RSSI + identity only; the connect-to-identify branch probes
         * empty-payload results.
         */payload: Data, rssi: Int32) {
        self.address = address
        self.payload = payload
        self.rssi = rssi
    }

    

    
}

#if compiler(>=6)
extension FfiScanResult: Sendable {}
#endif

#if swift(>=5.8)
@_documentation(visibility: private)
#endif
public struct FfiConverterTypeFfiScanResult: FfiConverterRustBuffer {
    public static func read(from buf: inout (data: Data, offset: Data.Index)) throws -> FfiScanResult {
        return
            try FfiScanResult(
                address: FfiConverterString.read(from: &buf), 
                payload: FfiConverterData.read(from: &buf), 
                rssi: FfiConverterInt32.read(from: &buf)
        )
    }

    public static func write(_ value: FfiScanResult, into buf: inout [UInt8]) {
        FfiConverterString.write(value.address, into: &buf)
        FfiConverterData.write(value.payload, into: &buf)
        FfiConverterInt32.write(value.rssi, into: &buf)
    }
}


#if swift(>=5.8)
@_documentation(visibility: private)
#endif
public func FfiConverterTypeFfiScanResult_lift(_ buf: RustBuffer) throws -> FfiScanResult {
    return try FfiConverterTypeFfiScanResult.lift(buf)
}

#if swift(>=5.8)
@_documentation(visibility: private)
#endif
public func FfiConverterTypeFfiScanResult_lower(_ value: FfiScanResult) -> RustBuffer {
    return FfiConverterTypeFfiScanResult.lower(value)
}


/**
 * Errors that can cross the UniFFI boundary from the Swift adapters back into
 * the Rust engine. UniFFI requires every foreign-trait method to return
 * `Result<_, CompatibleError>`; this is the compatible error type.
 *
 * `Timeout` carries BLE-RT-C003 (IOS_DESIGN §4 / AC-6): the `gatt_read` path
 * in the Swift `IosBleAdapter` enforces a hard call-timeout (default 10 s) and
 * surfaces it here as a typed error — no hang, no leaked task.
 */
public enum IrisFfiError: Swift.Error, Equatable, Hashable, Foundation.LocalizedError {

    
    
    case NotSupported
    case PermissionDenied
    case AdapterOff
    case DeviceNotFound
    case GattFailure(String
    )
    case Timeout
    case IoError(String
    )
    case InvalidArgument(String
    )
    case Transport(String
    )

    

    

    
    public var errorDescription: String? {
        String(reflecting: self)
    }
    
}

#if compiler(>=6)
extension IrisFfiError: Sendable {}
#endif

#if swift(>=5.8)
@_documentation(visibility: private)
#endif
public struct FfiConverterTypeIrisFfiError: FfiConverterRustBuffer {
    typealias SwiftType = IrisFfiError

    public static func read(from buf: inout (data: Data, offset: Data.Index)) throws -> IrisFfiError {
        let variant: Int32 = try readInt(&buf)
        switch variant {

        

        
        case 1: return .NotSupported
        case 2: return .PermissionDenied
        case 3: return .AdapterOff
        case 4: return .DeviceNotFound
        case 5: return .GattFailure(
            try FfiConverterString.read(from: &buf)
            )
        case 6: return .Timeout
        case 7: return .IoError(
            try FfiConverterString.read(from: &buf)
            )
        case 8: return .InvalidArgument(
            try FfiConverterString.read(from: &buf)
            )
        case 9: return .Transport(
            try FfiConverterString.read(from: &buf)
            )

         default: throw UniffiInternalError.unexpectedEnumCase
        }
    }

    public static func write(_ value: IrisFfiError, into buf: inout [UInt8]) {
        switch value {

        

        
        
        case .NotSupported:
            writeInt(&buf, Int32(1))
        
        
        case .PermissionDenied:
            writeInt(&buf, Int32(2))
        
        
        case .AdapterOff:
            writeInt(&buf, Int32(3))
        
        
        case .DeviceNotFound:
            writeInt(&buf, Int32(4))
        
        
        case let .GattFailure(v1):
            writeInt(&buf, Int32(5))
            FfiConverterString.write(v1, into: &buf)
            
        
        case .Timeout:
            writeInt(&buf, Int32(6))
        
        
        case let .IoError(v1):
            writeInt(&buf, Int32(7))
            FfiConverterString.write(v1, into: &buf)
            
        
        case let .InvalidArgument(v1):
            writeInt(&buf, Int32(8))
            FfiConverterString.write(v1, into: &buf)
            
        
        case let .Transport(v1):
            writeInt(&buf, Int32(9))
            FfiConverterString.write(v1, into: &buf)
            
        }
    }
}


#if swift(>=5.8)
@_documentation(visibility: private)
#endif
public func FfiConverterTypeIrisFfiError_lift(_ buf: RustBuffer) throws -> IrisFfiError {
    return try FfiConverterTypeIrisFfiError.lift(buf)
}

#if swift(>=5.8)
@_documentation(visibility: private)
#endif
public func FfiConverterTypeIrisFfiError_lower(_ value: IrisFfiError) -> RustBuffer {
    return FfiConverterTypeIrisFfiError.lower(value)
}

#if swift(>=5.8)
@_documentation(visibility: private)
#endif
fileprivate struct FfiConverterSequenceTypeFfiGattWriteEvent: FfiConverterRustBuffer {
    typealias SwiftType = [FfiGattWriteEvent]

    public static func write(_ value: [FfiGattWriteEvent], into buf: inout [UInt8]) {
        let len = Int32(value.count)
        writeInt(&buf, len)
        for item in value {
            FfiConverterTypeFfiGattWriteEvent.write(item, into: &buf)
        }
    }

    public static func read(from buf: inout (data: Data, offset: Data.Index)) throws -> [FfiGattWriteEvent] {
        let len: Int32 = try readInt(&buf)
        var seq = [FfiGattWriteEvent]()
        seq.reserveCapacity(Int(len))
        for _ in 0 ..< len {
            seq.append(try FfiConverterTypeFfiGattWriteEvent.read(from: &buf))
        }
        return seq
    }
}

#if swift(>=5.8)
@_documentation(visibility: private)
#endif
fileprivate struct FfiConverterSequenceTypeFfiScanResult: FfiConverterRustBuffer {
    typealias SwiftType = [FfiScanResult]

    public static func write(_ value: [FfiScanResult], into buf: inout [UInt8]) {
        let len = Int32(value.count)
        writeInt(&buf, len)
        for item in value {
            FfiConverterTypeFfiScanResult.write(item, into: &buf)
        }
    }

    public static func read(from buf: inout (data: Data, offset: Data.Index)) throws -> [FfiScanResult] {
        let len: Int32 = try readInt(&buf)
        var seq = [FfiScanResult]()
        seq.reserveCapacity(Int(len))
        for _ in 0 ..< len {
            seq.append(try FfiConverterTypeFfiScanResult.read(from: &buf))
        }
        return seq
    }
}
private let UNIFFI_RUST_FUTURE_POLL_READY: Int8 = 0
private let UNIFFI_RUST_FUTURE_POLL_WAKE: Int8 = 1

fileprivate let uniffiContinuationHandleMap = UniffiHandleMap<UnsafeContinuation<Int8, Never>>()

fileprivate func uniffiRustCallAsync<F, T>(
    rustFutureFunc: () -> UInt64,
    pollFunc: (UInt64, @escaping UniffiRustFutureContinuationCallback, UInt64) -> (),
    completeFunc: (UInt64, UnsafeMutablePointer<RustCallStatus>) -> F,
    freeFunc: (UInt64) -> (),
    liftFunc: (F) throws -> T,
    errorHandler: ((RustBuffer) throws -> Swift.Error)?
) async throws -> T {
    // Make sure to call the ensure init function since future creation doesn't have a
    // RustCallStatus param, so doesn't use makeRustCall()
    uniffiEnsureIrisCoreInitialized()
    let rustFuture = rustFutureFunc()
    defer {
        freeFunc(rustFuture)
    }
    var pollResult: Int8;
    repeat {
        pollResult = await withUnsafeContinuation {
            pollFunc(
                rustFuture,
                { handle, pollResult in
                    uniffiFutureContinuationCallback(handle: handle, pollResult: pollResult)
                },
                uniffiContinuationHandleMap.insert(obj: $0)
            )
        }
    } while pollResult != UNIFFI_RUST_FUTURE_POLL_READY

    return try liftFunc(makeRustCall(
        { completeFunc(rustFuture, $0) },
        errorHandler: errorHandler
    ))
}

// Callback handlers for an async calls.  These are invoked by Rust when the future is ready.  They
// lift the return value or error and resume the suspended function.
fileprivate func uniffiFutureContinuationCallback(handle: UInt64, pollResult: Int8) {
    if let continuation = try? uniffiContinuationHandleMap.remove(handle: handle) {
        continuation.resume(returning: pollResult)
    } else {
        print("uniffiFutureContinuationCallback invalid handle")
    }
}
private func uniffiTraitInterfaceCallAsync<T>(
    makeCall: @escaping () async throws -> T,
    handleSuccess: @escaping (T) -> (),
    handleError: @escaping (Int8, RustBuffer) -> (),
    droppedCallback: UnsafeMutablePointer<UniffiForeignFutureDroppedCallbackStruct>
) {
    let task = Task {
        // Note: it's important we call either `handleSuccess` or `handleError` exactly once.  Each
        // call consumes an Arc reference, which means there should be no possibility of a double
        // call.  The following code is structured so that will will never call both `handleSuccess`
        // and `handleError`, even in the face of weird errors.
        //
        // On platforms that need extra machinery to make C-ABI calls, like JNA or ctypes, it's
        // possible that we fail to make either call.  However, it doesn't seem like this is
        // possible on Swift since swift can just make the C call directly.
        var callResult: T
        do {
            callResult = try await makeCall()
        } catch {
            handleError(CALL_UNEXPECTED_ERROR, FfiConverterString.lower(String(describing: error)))
            return
        }
        handleSuccess(callResult)
    }
    let handle = UNIFFI_FOREIGN_FUTURE_HANDLE_MAP.insert(obj: task)
    droppedCallback.pointee = UniffiForeignFutureDroppedCallbackStruct(
        handle: handle,
        free: uniffiForeignFutureDroppedCallback
    )
}

private func uniffiTraitInterfaceCallAsyncWithError<T, E>(
    makeCall: @escaping () async throws -> T,
    handleSuccess: @escaping (T) -> (),
    handleError: @escaping (Int8, RustBuffer) -> (),
    lowerError: @escaping (E) -> RustBuffer,
    droppedCallback: UnsafeMutablePointer<UniffiForeignFutureDroppedCallbackStruct>
) {
    let task = Task {
        // See the note in uniffiTraitInterfaceCallAsync for details on `handleSuccess` and
        // `handleError`.
        var callResult: T
        do {
            callResult = try await makeCall()
        } catch let error as E {
            handleError(CALL_ERROR, lowerError(error))
            return
        } catch {
            handleError(CALL_UNEXPECTED_ERROR, FfiConverterString.lower(String(describing: error)))
            return
        }
        handleSuccess(callResult)
    }
    let handle = UNIFFI_FOREIGN_FUTURE_HANDLE_MAP.insert(obj: task)
    droppedCallback.pointee = UniffiForeignFutureDroppedCallbackStruct(
        handle: handle,
        free: uniffiForeignFutureDroppedCallback
    )
}

// Borrow the callback handle map implementation to store foreign future handles
// TODO: consolidate the handle-map code (https://github.com/mozilla/uniffi-rs/pull/1823)
fileprivate let UNIFFI_FOREIGN_FUTURE_HANDLE_MAP = UniffiHandleMap<UniffiForeignFutureTask>()

// Protocol for tasks that handle foreign futures.
//
// Defining a protocol allows all tasks to be stored in the same handle map.  This can't be done
// with the task object itself, since has generic parameters.
fileprivate protocol UniffiForeignFutureTask {
    func cancel()
}

extension Task: UniffiForeignFutureTask {}

private func uniffiForeignFutureDroppedCallback(handle: UInt64) {
    do {
        let task = try UNIFFI_FOREIGN_FUTURE_HANDLE_MAP.remove(handle: handle)
        // Set the cancellation flag on the task.  If it's still running, the code can check the
        // cancellation flag or call `Task.checkCancellation()`.  If the task has completed, this is
        // a no-op.
        task.cancel()
    } catch {
        print("uniffiForeignFutureDroppedCallback: handle missing from handlemap")
    }
}

// For testing
public func uniffiForeignFutureHandleCountIrisCore() -> Int {
    UNIFFI_FOREIGN_FUTURE_HANDLE_MAP.count
}

private enum InitializationResult {
    case ok
    case contractVersionMismatch
    case apiChecksumMismatch
}
// Use a global variable to perform the versioning checks. Swift ensures that
// the code inside is only computed once.
private let initializationResult: InitializationResult = {
    // Get the bindings contract version from our ComponentInterface
    let bindings_contract_version = 30
    // Get the scaffolding contract version by calling the into the dylib
    let scaffolding_contract_version = ffi_IrisCore_uniffi_contract_version()
    if bindings_contract_version != scaffolding_contract_version {
        return InitializationResult.contractVersionMismatch
    }
    if (uniffi_IrisCore_checksum_method_ffiinboxlistener_on_message() != 27859) {
        return InitializationResult.apiChecksumMismatch
    }
    if (uniffi_IrisCore_checksum_method_irisengine_node_id() != 30899) {
        return InitializationResult.apiChecksumMismatch
    }
    if (uniffi_IrisCore_checksum_method_irisengine_send_text() != 48965) {
        return InitializationResult.apiChecksumMismatch
    }
    if (uniffi_IrisCore_checksum_method_irisengine_set_body_renderer() != 34457) {
        return InitializationResult.apiChecksumMismatch
    }
    if (uniffi_IrisCore_checksum_method_irisengine_start_all() != 3665) {
        return InitializationResult.apiChecksumMismatch
    }
    if (uniffi_IrisCore_checksum_method_irisengine_stop_all() != 62335) {
        return InitializationResult.apiChecksumMismatch
    }
    if (uniffi_IrisCore_checksum_method_irisengine_subscribe_inbox() != 7759) {
        return InitializationResult.apiChecksumMismatch
    }
    if (uniffi_IrisCore_checksum_method_ffibleadapter_start_scan() != 16564) {
        return InitializationResult.apiChecksumMismatch
    }
    if (uniffi_IrisCore_checksum_method_ffibleadapter_stop_scan() != 7107) {
        return InitializationResult.apiChecksumMismatch
    }
    if (uniffi_IrisCore_checksum_method_ffibleadapter_start_advertising() != 45406) {
        return InitializationResult.apiChecksumMismatch
    }
    if (uniffi_IrisCore_checksum_method_ffibleadapter_stop_advertising() != 28032) {
        return InitializationResult.apiChecksumMismatch
    }
    if (uniffi_IrisCore_checksum_method_ffibleadapter_connect_gatt() != 4338) {
        return InitializationResult.apiChecksumMismatch
    }
    if (uniffi_IrisCore_checksum_method_ffibleadapter_disconnect_gatt() != 60834) {
        return InitializationResult.apiChecksumMismatch
    }
    if (uniffi_IrisCore_checksum_method_ffibleadapter_gatt_write() != 43203) {
        return InitializationResult.apiChecksumMismatch
    }
    if (uniffi_IrisCore_checksum_method_ffibleadapter_gatt_read() != 7859) {
        return InitializationResult.apiChecksumMismatch
    }
    if (uniffi_IrisCore_checksum_method_ffibleadapter_set_mtu() != 28755) {
        return InitializationResult.apiChecksumMismatch
    }
    if (uniffi_IrisCore_checksum_method_ffibleadapter_incoming_gatt_writes() != 33164) {
        return InitializationResult.apiChecksumMismatch
    }
    if (uniffi_IrisCore_checksum_method_ffibleadapter_scan_results() != 52108) {
        return InitializationResult.apiChecksumMismatch
    }
    if (uniffi_IrisCore_checksum_method_irisbody_summarize() != 22203) {
        return InitializationResult.apiChecksumMismatch
    }
    if (uniffi_IrisCore_checksum_method_irisbody_describe() != 27901) {
        return InitializationResult.apiChecksumMismatch
    }
    if (uniffi_IrisCore_checksum_constructor_irisengine_new() != 4683) {
        return InitializationResult.apiChecksumMismatch
    }

    uniffiCallbackInitFfiBleAdapter()
    uniffiCallbackInitFfiInboxListener()
    uniffiCallbackInitIrisBody()
    return InitializationResult.ok
}()

// Make the ensure init function public so that other modules which have external type references to
// our types can call it.
public func uniffiEnsureIrisCoreInitialized() {
    switch initializationResult {
    case .ok:
        break
    case .contractVersionMismatch:
        fatalError("UniFFI contract version mismatch: try cleaning and rebuilding your project")
    case .apiChecksumMismatch:
        fatalError("UniFFI API checksum mismatch: try cleaning and rebuilding your project")
    }
}

// swiftlint:enable all